### ISSUE TITLE
Switch to new VIP-Coding-Standards PHPCS rules

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#1032]
As [noted](https://github.com/Automattic/vip-go-mu-plugins/pull/766#issuecomment-444111235) by @GaryJones, this repo is still on the old PHPCS rules - we should switch over to https://github.com/Automattic/VIP-Coding-Standards instead, which is where active development is going.

**Comment by joshbetz** [comment]
The old WordPress-VIP rules have been deleted from the WPCS repo https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1551
