### ISSUE TITLE
Disable plugin and theme install/update in WP-Admin

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/vip-go-mu-plugins#1033]
With the filesystem on a local Vagrant setup now mirroring VIP Go, users aren't able to upload plugins directly via the wp-admin dashboard or update existing plugins. Trying to do so will create a `Could not create directory.` warning. We should remove these items from the dashboard as a result to mirror the setup of a VIP site.

**Local environment**
<img width="664" alt="screen shot 2018-12-04 at 3 05 20 pm" src="https://user-images.githubusercontent.com/7240478/49476057-1c05bc00-f7d6-11e8-9193-9e3c55e2588c.png">

**Go Environment**
<img width="367" alt="screen shot 2018-12-04 at 3 05 37 pm" src="https://user-images.githubusercontent.com/7240478/49476065-2031d980-f7d6-11e8-9b10-7f27cca3d4a9.png">

**Comment by joshbetz** [comment]
There are some constants that need to go in `wp-config.php`:

```
define( 'DISALLOW_FILE_EDIT', true );
define( 'DISALLOW_FILE_MODS', true );
define( 'AUTOMATIC_UPDATER_DISABLED', true );
```

I think we just have to document this because we don't control `wp-config.php` in `mu-plugins`.

**Comment by BrookeDot** [comment]
This is true for Themes as well:

**Local:**
![local_themes](https://user-images.githubusercontent.com/150348/49671553-282f8a80-fa1d-11e8-9541-d01ae2fab85f.png)

**VIP Go:**
![go_themes](https://user-images.githubusercontent.com/150348/49671601-4ac1a380-fa1d-11e8-9294-9e330d16a202.png)

**Comment by BrookeDot** [comment]
> There are some constants that need to go in `wp-config.php`:
> 
> ```
> define( 'DISALLOW_FILE_EDIT', true );
> define( 'DISALLOW_FILE_MODS', true );
> define( 'AUTOMATIC_UPDATER_DISABLED', true );
> ```
> 
> I think we just have to document this because we don't control `wp-config.php` in `mu-plugins`.

Thanks @joshbetz that works as expected. I'll get https://vip.wordpress.com/documentation/vip-go/local-vip-go-development-environment updated!

**Comment by BrookeDot** [comment]
Docs update, closing:
https://vip.wordpress.com/documentation/vip-go/local-vip-go-development-environment/#step-4-update-your-wp-config-file
