### ISSUE TITLE
Make VIP featured plugins error more accurate and less scary

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#1041]
https://github.com/Automattic/vip-go-mu-plugins/blob/7d01659e03c6b25a90808681844e2b5cf0ddb6a4/vip-plugins/vip-plugins.php#L59

Can we change the wording to:

> Unable to display VIP featured plugins; try refreshing this page in a few minutes. If this error persists, please contact VIP Support.

i.e. use "display" instead of "load" so it's clearer that this is not causing an issue with the functionality of the plugins in the website

**Comment by mjangda** [comment]
Fixed in #1042
