### ISSUE TITLE
Site `queue_post_purge` being called on file upload post IDs

### ISSUE THREAD

**Issue by darthhexx** [Automattic/vip-go-mu-plugins#1047]
The following purges are being fired off for each uploaded file via `wp-admin`:
```
Request to http://192.0.88.197/wp-content/uploads/<file path>
Request to http://192.0.88.197/<file-name>/
Request to http://192.0.88.197/
Request to http://192.0.88.197/feed/rdf/
Request to http://192.0.88.197/feed/rss/
Request to http://192.0.88.197/feed/
Request to http://192.0.88.197/feed/atom/
Request to http://192.0.88.197/comments/feed/atom/
Request to http://192.0.88.197/comments/feed/
Request to http://192.0.88.197/feed/attachment_id=<ID>
```
Stack trace:
```
#0 /var/www/wp-includes/class-wp-hook.php(288): WPCOM_VIP_Cache_Manager->queue_post_purge(566)
#1 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/wp-includes/post.php(6052): do_action('clean_post_cach...', 566, Object(WP_Post))
#4 /var/www/wp-includes/post.php(3644): clean_post_cache(Object(WP_Post))
#5 /var/www/wp-includes/post.php(5082): wp_insert_post(Array, true)
#6 /var/www/wp-admin/includes/media.php(382): wp_insert_attachment(Array, '/tmp/uploads/20...', 0, true)
#7 /var/www/wp-admin/async-upload.php(81): media_handle_upload('async-upload', 0)
```

I can't see the need for this at all, am I missing something?

IMO we should check for and exclude any post IDs where the `post type == 'attachment' && post_date == post_modified` in the VIP Cache Manager.

**Comment by darthhexx** [comment]
@hanifn I've upped the severity of this issue, because it is affecting production. Please can you ensure this issue, which I think was introduced with the WP Filesystem API changes, gets fixed as soon as possible. /cc @mjangda

**Comment by darthhexx** [comment]
Perfect, thanks Mo. I never looked into it further than reporting the behaviour and of course made some assumptions on the source :)

**Comment by hanifn** [comment]
@darthhexx  I have a PR ready with the changes you recommended. Basically skipping the purges on new files. Is there any other scenarios where we would like too skip some of the cache purges? @mjangda mentioned something about the feed URLs but I'm not entirely clear on the specifics of that.

**Comment by darthhexx** [comment]
I noticed this was deployed. Thanks!

The feed urls would be any feeds that would have _not_ been changed due to an image being replaced, making it pointless to purge them.
