### ISSUE TITLE
WP_Filesystem_VIP blocks local core upgrades

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1054]
This can be pretty annoying to work around:

```
$ wp core update
Updating to version 5.0.2 (en_US)...
Using cached file '/home/vagrant/.wp-cli/cache/core/wordpress-5.0.2-new-bundled-en_US.zip'...
Unpacking the update...
Warning: The `/vagrant/www/wordpress-default/public_html/wp-content/upgrade/wp_5c23bc476bff2` file cannot be managed by the `Automattic\VIP\Files\WP_Filesystem_VIP` class. Writes are only allowed for the `/uploads` and `/tmp` directories and reads can be performed everywhere. in /vagrant/www/wordpress-default/public_html/wp-content/mu-plugins/files/class-wp-filesystem-vip.php on line 59
Warning: The `/vagrant/www/wordpress-default/public_html/wp-content/upgrade/wp_5c23bc476bff2` file cannot be managed by the `Automattic\VIP\Files\WP_Filesystem_VIP` class. Writes are only allowed for the `/uploads` and `/tmp` directories and reads can be performed everywhere. in /vagrant/www/wordpress-default/public_html/wp-content/mu-plugins/files/class-wp-filesystem-vip.php on line 59
Error: Could not create directory.
```

**Comment by cameronterry** [comment]
For any one who stumbles upon this in the meantime; as a very temporary workaround, you can add `return;` to the `a8c-files.php` file here after the two comment blocks to temporarily disable VIP Filesystem;

https://github.com/Automattic/vip-go-mu-plugins/blob/e329664808376f380934613bb78cafa406cb7de0/a8c-files.php#L14

After this, you can use the WP CLI to perform Core, plugin, and theme updates.

**Comment by schlessera** [comment]
@mjangda I saw you were one of the original developers of the stream wrapper functionality that introduced this changes that is breaking WP-CLI behavior.

I'm the maintainer of WP-CLI and am interested in discussing a solution for this. Let me know if this requires changes in WP-CLI for a work-around.

**Comment by mjangda** [comment]
Thanks @schlessera; thanks for the offer to help!

This is a bug in our implementation / environment setup so not something we should add a workaround for in WP-CLI.

**Comment by jonathanstegall** [comment]
I've been wondering if this is related: my local environment won't log anything in my wp-content/debug.log file, even when `define( 'WP_DEBUG_LOG', true );` is present in wp-config.php. Adding the fix above doesn't change this behavior, but I wonder if anyone else has run into it?

**Comment by paulschreiber** [comment]
Any update on this?

**Comment by hrkhal** [comment]
Can progress be made on this? It's not ideal having to return early from an mu plugin to allow core upgrades in our local/testing envs.
