### ISSUE TITLE
Optimise jp_sitemap_cron_hook cron event with a setting

### ISSUE THREAD

**Issue by darthhexx** [Automattic/vip-go-mu-plugins#1058]
This cron job keeps coming up on the radar and we can optimise it with the JP_SITEMAP_BATCH_SIZE constant, which is currently defaulting to 50.

That means queries like this run thousands of times in batches of 50:
https://github.com/Automattic/jetpack/blob/aec7b473b7dc0289149655facfb5f20bbbc89600/modules/sitemaps/sitemap-librarian.php#L329

I think it would be fine to globally increase the limit. Thoughts?

**Comment by nickdaugherty** [comment]
Seems safe to bump up the batch size, do you have an idea on what the idea size is?

**Comment by darthhexx** [comment]
I would be guessing, as I haven't profiled the code, but 200 would probably be a good start.

**Comment by nickdaugherty** [comment]
That sounds safe and reasonable to me.

**Comment by mjangda** [comment]
The batch size used to be a 1000 but was dropped down due to memory issues: https://github.com/Automattic/jetpack/pull/7929

We can bump to 200 and see how it goes.
