### ISSUE TITLE
PHP 7.3 Compat: Continue Targeting Switch issues Warning

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-go-mu-plugins#1064]
>  _continue_ statements targeting _switch_ control flow structures will now generate a warning. In PHP such _continue_ statements are equivalent to _break_, while they behave as _continue 2_ in other languages. 

http://php.net/manual/en/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch

https://github.com/Automattic/vip-go-mu-plugins/blob/f5fe1d7af8aef9c115f3699980bdba20cbbdfaca/shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php#L817
https://github.com/Automattic/vip-go-mu-plugins/blob/f5fe1d7af8aef9c115f3699980bdba20cbbdfaca/shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php#L831

I think in both cases, this can be `break`.

**Comment by mjangda** [comment]
I think we'll want `continue 3` to match the other cases (e.g. `year` and `default`)?

**Comment by trepmal** [comment]
Ah, that does make more sense :)
