### ISSUE TITLE
Should not assume `get_query_var()` returns string

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-go-mu-plugins#1087]
https://github.com/Automattic/vip-go-mu-plugins/blob/ec90d4b64a2dde6dd432a54e8159195e6b5980fb/shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php#L600

Specifically this part: `explode( ',', get_query_var( $tax_query_var ) )`

In one recent case, the URL had `category[]=term` in it. Those two innocent looking little brackets racked up quite a few warnings.

**Comment by sjinks** [comment]
The code no longer exists, closing.
