### ISSUE TITLE
Introduce `vip://` Stream Wrapper

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1102]
Use a stream wrapper to facilitate communication with the Files Service rather than specific hooks.

Props https://github.com/humanmade/S3-Uploads and the Human Made team for the inspiration and guidance.

**Comment by GaryJones** [comment]
@hanifn Is any remaining work being tracked elsewhere? Can this be closed?

**Comment by hanifn** [comment]
@GaryJones This epic is pretty much completed. I'll close this.
