### ISSUE TITLE
Lockout: Implement base functionality

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1112]
When the `VIP_LOCKOUT_STATE` constant is defined and set to `warning`, we should:

- display an admin notice to **users with the `manage_options` capability** with whatever message is set in the `VIP_LOCKOUT_MESSAGE` constant.
- We should keep track of which users see a lockout message and when. We can track the seen/not seen state as one user meta entry and time as another user meta entry.
- This should not apply to VIP Support users.

When the `VIP_LOCKOUT_STATE` constant is defined and set to `locked`, we should:

- display an admin notice to **all users** with whatever message is set in the `VIP_LOCKOUT_MESSAGE` constant.
- remove all caps from users except `read` (so they can't take any action on the site).
- This should not apply to VIP Support users.

If the `VIP_LOCKOUT_STATE` constant is not set or set to another value, we should do nothing.

---

Other notes:

- We may want to use anonymous functions as callbacks for `add_action`/`add_filter` to make them harder to unhook.

**Comment by hanifn** [comment]
> * remove all caps from users except `read` (so they can't take any action on the site).

Wouldn't this be permanent a change? I'm using we'll have to use `remove_cap` for this. Sounds like it would be hard to add them back in. Is there any way to temporarily disable caps?

Or maybe just do how they do it on WPCOM and just `die()`

**Comment by mjangda** [comment]
> Is there any way to temporarily disable caps?

We can use the `user_has_cap` filter to dynamically modify the caps: https://developer.wordpress.org/reference/hooks/user_has_cap/ (see `_wpcom_vip_user_has_cap` on WP.com as an example).
