### ISSUE TITLE
Stream Wrapper: opendir triggers a warning

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1116]
```
wp> opendir( 'vip://wp-content/uploads/test/' );
Warning: opendir(vip://wp-content/uploads/test/): failed to open dir: "Automattic\VIP\Files\VIP_Filesystem_Stream_Wrapper::dir_opendir" call failed
```

**Comment by mjangda** [comment]
We should probably add `dir_opendir` which just calls `return false` since we don't really support directory operations (like iterating).

**Comment by andrewfleming** [comment]
The same is true for `scandir()`.

```
wp> scandir('vip://wp-content/uploads/sites/3');
Warning: scandir(vip://wp-content/uploads/sites/3): failed to open dir: "Automattic\VIP\Files\VIP_Filesystem_Stream_Wrapper::dir_opendir" call failed
bool(false)
```
This issue appears to be blocking plugins which clone sites within a multisite network from recursively copying media files. What alternatives do we have for situations requiring iteration over directories?

**Comment by shantanu2704** [comment]
This issue also appears to affect plugins that store styles within a new directory inside `wp-content/uploads`. So, a CSS file can't be written to `wp-content/uploads/dynamic-css/filename.css` and a URL like https://example.go-vip.net/wp-content/uploads/dynamic-styles-css/filename.css returns an HTTP 404

**Comment by rebeccahum** [comment]
What's the issue with triggering a warning if it's not supported?
