### ISSUE TITLE
Disable theme install UI

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#112]
Since everything is in version control, there should never be a UI to upload or browse themes to install.

![theme-browser](https://cldup.com/v2WM6mMCNY-3000x3000.png)

![add-theme-button](https://cldup.com/kJVAZ95H5b-3000x3000.png)

/wp-admin/theme-install.php

**Comment by mjangda** [comment]
I don't see the upload option any more; closing.
