### ISSUE TITLE
Vary Cache: Improvements to group get/set functionality

### ISSUE THREAD

**Issue by dchymko** [Automattic/vip-go-mu-plugins#1122]
We should enhance the group functions to make them more flexible for a variety of use cases:

- [x] Prefix the cookie value with a version `v1__group_--_value` to allow dynamic changes to the cookie over time, if needed (e.g. if we change the delimiter or change the structure).
- [x] Add a `register_group()` method to accept a single group
- [x] Change the group functions to work when the encrypted flag is set
- [x] Optimize the group parsing function to only load/run when required (i.e. if cookie has been parsed with no changes, skip)
- [x] Simplify `is_user_in_group` (a bit difficult to follow the logic)

**Comment by dchymko** [comment]
Cookie prefix added as part of #1127

**Comment by mjangda** [comment]
This is done.
