### ISSUE TITLE
Vary Cache: Validation and debugging improvements

### ISSUE THREAD

**Issue by dchymko** [Automattic/vip-go-mu-plugins#1123]
We should add validation to ensure that invalid use is handled or rejected

- [x] Validate that the group name and value are limited to alphanumerics, '-' and '_' (or escape them)
- [ ] Add tests on the public methods
- [x] Add debug mode which would include a custom header and also output in the footer source to assist with developer troubleshooting

**Comment by mjangda** [comment]
> Add tests on the public methods

There are some private / protected methods that we may want to add tests for as well.

**Comment by mjangda** [comment]
Going to close this out; we'll add more tests over time.
