### ISSUE TITLE
Skip plugins / themes when connecting Jetpack and Akismet

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#1162]
Otherwise site code can cause errors / unexpected behavior.

https://github.com/Automattic/vip-go-mu-plugins/blob/63df16d2d9bd74814120d1d206f46d52fd6d1847/vip-helpers/vip-migrations.php#L68

**Comment by rebeccahum** [comment]
Unneeded now with the Jetpack Connection Pilot which makes an API call.
