### ISSUE TITLE
Vary Cache: Add remove_user_from_group

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1163]
To support the use case where a user needs to be removed from a group.

Related: we should remove the cookie if the user was previously in groups but was then removed from them.

Initially discussed in #1160

**Comment by dchymko** [comment]
I think we'll either want to store the "original" groups in a 2nd variable when we first parse the cookie or in the empty check set_group_cookie(), and it the cookie came in with a value and if so, expire it.

**Comment by jamesmehorter** [comment]
+1 for this. For the use case of a paywall—when the user logs out they should no longer be in any 'paywall' group/segment. With the current code we need to create a segment for 'logged-out'.

**Comment by mjangda** [comment]
Closing as wontfix for now. We can revisit if/when we pick up additional work to the Vary Cache API.
