### ISSUE TITLE
WPCOM_VIP_CLI_Command::stop_the_insanity leads to PHP warnings in object-cache

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1171]
```
Notice: Undefined index: get in /chroot/var/www/wp-content/object-cache.php on line 252
```

We reset the `stats` property in the Object Cache object which has some pre-defined keys. Any `wp_cache_*` calls after calling `stop_the_insanity` lead to warnings.

Related #1170

**Comment by sjinks** [comment]
Fixed in #1512
