### ISSUE TITLE
Cron Control + 5.1 Hooks

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1179]
Thanks to @ethitter Cron Control will soon be able to use the new Cron hooks introduced in WordPress 5.1: https://github.com/Automattic/Cron-Control/pull/174

We're going to track work here to get this rolled out and deployed.

**Comment by GaryJones** [comment]
Work continued in https://github.com/Automattic/Cron-Control/pull/178.
