### ISSUE TITLE
Stream Wrapper: Cron event for updating filesize

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1182]
We should move the logic from the `update-filesize` CLI command to a recurring cron event so we can run it globally across all environments easily.

**Comment by hanifn** [comment]
I'm thinking that this cron job will be registered if we have set a constant, `VIP_STREAM_WRAPPER_UPDATE_FILESIZES` on a site. Or maybe even reuse the `VIP_FILESYSTEM_USE_STREAM_WRAPPER` flag?

How often do you think we should run this @mjangda?

**Comment by mjangda** [comment]
I think we can reuse the existing constant to keep things simple. 

And maybe a schedule of 5 or 10 mins?

**Comment by hanifn** [comment]
> And maybe a schedule of 5 or 10 mins?

So the job would run every 5 or 10 mins? When would it stop?

**Comment by mjangda** [comment]
> So the job would run every 5 or 10 mins?

Let's go with 5 mins. 

> When would it stop?

When all attachments have been processed. On the first run we should calculate the max ID and store that in an option.

Each job should process maybe a max of 1000 attachments per run and once we hit that original max ID we can unschedule the job (may also need to store an option to track that).

**Comment by mjangda** [comment]
This was the pseudocode we'd come up with earlier:

```
if ( get_option( 'vip_all_attachment_filesize_processed' ) ) {
    // unschedule job?
    return;
}

$max_id = get max ID from option or query for it if not in option. 
$start_index = get_option( 'vip_next_attachment_filesize_index', 0 );
$end_index = $start_index + $batch_size;

if ( $start_index > $max_id ) {
    update_option( 'vip_all_attachment_filesize_processed', 1 );
    // unschedule job?
    return;
]

// get attachments between ID start_index and end_index
// process them

update_option( 'vip_next_attachment_filesize_index', $end_index + 1 );
```
