### ISSUE TITLE
Avoid automatically creating the vip_meta_key_value index on huge sites

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#1188]
I installed a large database in my local environment and the schema update that was triggered automatically caused some problems. In most cases the index will already exist, so it won't be a problem. If possible, we might want to avoid automatically creating this index on sites with many millions of postmeta entries though.

https://github.com/Automattic/vip-go-mu-plugins/blob/master/schema.php#L12-L26

**Comment by sjinks** [comment]
Related: #2893
