### ISSUE TITLE
vip-go-mu-plugins-built as a Composer dependency on Packagist

### ISSUE THREAD

**Issue by johnbillion** [Automattic/vip-go-mu-plugins#1193]
One of the things we're struggling with a bit is managing the VIP Go plugins as part of our local development environments.

We're managing almost all other dependencies using Composer. Having a manual or shell-scripted step in the setup process for developers to install the VIP Go plugins feels out of place.

It would be great if the `vip-go-mu-plugins-built` repo was available as a Composer dependency on Packagist. That way it could be made added as a development dependency, developers could manage its installation and updates as part of the standard Composer development workflow, and the whole lot would be installed into `mu-plugins` using the `installer-paths` method provided by `oomphinc/composer-installers-extender`, which is pretty common for Composer-powered WordPress projects.

**Comment by johnbillion** [comment]
Clarification: This is just for managing this repo as a dependency for local development environments. It would have no effect on how this is deployed on VIP.

**Comment by mjangda** [comment]
Sounds like a good idea 👍 

> the whole lot would be installed into mu-plugins using the installer-paths method provided by oomphinc/composer-installers-extender, which is pretty common for Composer-powered WordPress projects.

This would be something that the project require-ing `vip-go-mu-plugins` would specify, correct? Or is there something we need to do in our composer file to allow for / simplify that?

**Comment by johnbillion** [comment]
> This would be something that the project require-ing `vip-go-mu-plugins` would specify, correct?

Correct. Nothing that's the responsibility of this package.

**Comment by GaryJones** [comment]
Appears to be fixed with #1195.

**Comment by johnbillion** [comment]
The package isn't actually on Packagist yet, but the change in #1195 enables it to be. The stickler in me says this should be re-opened until the package is actually published on Packagist :-)

**Comment by jenkoian** [comment]
Any update on this? Thanks.

**Comment by GaryJones** [comment]
I've requested that this be done.

**Comment by mjangda** [comment]
Sorry for the wait everyone; the "built" copy of this repo is now available on Packagist: https://packagist.org/packages/automattic/vip-go-mu-plugins

Thanks for the help @johnbillion and @GaryJones!
