### ISSUE TITLE
Missing cleanup of _encloseme in postmeta

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/vip-go-mu-plugins#1194]
We disable the hook `do_pings` for performance reasons due to the query it runs on every `publish_post` hook:
https://github.com/Automattic/vip-go-mu-plugins/blob/da7fcd24b773e1957687c6eb56f0b56ddd402d9e/performance/do-pings.php#L12

However, this causes the `do_all_pings()` cleanup function to not run anymore:
https://github.com/WordPress/WordPress/blob/1e925a5ae3faccad31c48c810af3954d01a60f0e/wp-includes/comment.php#L2626

Unfortunately, that can lead to sites with potentially hundreds of thousands rows with the `_encloseme` key on the postmeta table and cause performance issues on simple meta queries like:

```
SELECT post_id, meta_key, meta_value FROM wp_postmeta WHERE post_id IN (x) ORDER BY meta_id ASC
```

I think we should have a recurring cron job (perhaps, daily or weekly?) to run `do_all_pings()` so we do the cleanup regardless.

cc @rogertheriault

**Comment by WPprodigy** [comment]
Running `do_all_pings()` would be a change in functionality from what is currently happening on VIP sites. Pings and trackbacks would start occurring, while currently they are just disabled it seems?

Looking into your notes in ZD, it looks like perhaps the main problem is how the `_encloseme` meta is continually created: https://github.com/WordPress/WordPress/blob/71cf332e6569f0ac2f263ce9b2168644942f5534/wp-includes/post.php#L6580

So perhaps we could just filter in here and stop the meta from being added: https://github.com/WordPress/WordPress/blob/640c90d35d6ea7bce258201a9005defe6d4543f9/wp-includes/meta.php#L72-L75

**Comment by WPprodigy** [comment]
Oh wait. I think there's a good case here for a core change here: https://github.com/WordPress/WordPress/blob/71cf332e6569f0ac2f263ce9b2168644942f5534/wp-includes/post.php#L6580

Using the 4th param of `add_post_meta()` would ensure multiple entries aren't created. I can't imagine why you would need multiple `_encloseme` metas.

In the mean time we could use the above filter to ensure only 1 is created, but a core trac ticket is probably valid here.

**Comment by rebeccahum** [comment]
Thanks for reviving, this dropped off my radar.  Created a core trac ticket, but not sure if it will be applicable if WP is not expecting us to disable pings: https://core.trac.wordpress.org/ticket/48014#ticket
