### ISSUE TITLE
wp-cli: Default posts_per_page to 20 or whatever the admin limit is

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#1205]
We limit bulk editing in wp-admin to 20 posts. It would likely make sense to default things like `wp post list` to show 20 posts at a time -- even if we let you override it by passing `--posts_per_page=-1`. The default of no limit can execute a very slow query if you happen to forget to set that limit on large sites.

**Comment by nickdaugherty** [comment]
Actually let's go a different direction on this for now - let's reject `wp post list` commands that have no `--posts_per_page` specified, since it's not straightforward to filter the args in WP CLI, and since it will remove any behind-the-scenes magic.
