### ISSUE TITLE
Add a CLI command to purge the site cache

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#126]
It would be useful for us to be able to purge the Varnish cache for pages and/or files from a CLI command.

Some args that would be useful for this:

- local (i.e. sandbox) vs global (i.e. "production) caches
- full cache vs specific URL

**Comment by rebeccahum** [comment]
This is completed: https://docs.wpvip.com/how-tos/flush-the-page-cache/
