### ISSUE TITLE
Don't run Jetpack connect on vip_after_data_migration

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#1263]
In #1936 and #1937 we're looking to retain Jetpack connection. If that's the case, we don't need to re-run the Jetpack connection login via the `vip_after_data_migration` action in mu-plugins.

We'll want to modify the behaviour to accommodate that.

**Comment by rebeccahum** [comment]
I think this is no longer applicable because of https://github.com/Automattic/vip-go-mu-plugins/blob/fdd99cf535e55eeda46d7a11a4cbb1603d8bc666/vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php#L117.
