### ISSUE TITLE
Add link to General Ticket Guidelines

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#1297]
From @tessaneedham, via P2 (https://wp.me/p6jPRI-2ew):

We have recently published a General Ticket Guidelines doc, and have found (anecdotally) that when clients refer to it, we're able to help our clients more quickly as all the required information is present.

Could we please add a link to this doc from within the Contact WordPress.com VIP Support form in wp-admin? Right now, it displays a very vague message to “Please be descriptive”:

<img width="610" alt="screen-shot-2019-06-14-at-10 55 11-am" src="https://user-images.githubusercontent.com/233434/60806002-bcabc800-a179-11e9-9302-39ebafafabbc.png">

Perhaps we might add:

* A link under the "Details" field, link text "Help us help you faster, please read our ticket guidelines"
* Change the prompt to "Include as much information as possible, including relevant domain names and your investigation so far".

@tessaneedham I am open to changes on either the link text or the prompt text…

**Comment by tessaneedham** [comment]
Thanks @simonwheatley! 

As for the text, I'm borrowing Mo's words from the P2 post and mixing with yours above, to come up with:

Details field:  Please include as much information possible about the issue, including relevant domain names and your investigation so far.

Note underneath: Note: please read our [full ticket guidelines](https://wpvip.com/documentation/general-ticket-guidelines/) for faster, more timely resolutions.

I'm also wondering if it would be helpful for the details field to be a larger box? I wonder if the smallish size of the field is discouraging folks from writing much, though I have no data to back this up.

Thoughts?

**Comment by simonwheatley** [comment]
Definitely let’s try making the box larger 👍

**Comment by sjinks** [comment]
@simonwheatley @tessaneedham does it look good if I do it this way?

<img width="619" alt="Screenshot 2022-06-26 at 11 28 56" src="https://user-images.githubusercontent.com/7810770/175806211-c90ae569-4be1-4b4a-90e5-366f2c0fce3e.png">

**Comment by mjangda** [comment]
Looks good 👍

**Comment by GaryJones** [comment]
Properly fixed in #3550.
