### ISSUE TITLE
Remove artifact comment

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-go-mu-plugins#1303]
line 89:

https://github.com/Automattic/vip-go-mu-plugins/blob/ae0dbabcee7eadd7d3e94c60dde756dcd0a26705/files/class-api-client.php#L87-L91

moments later…

https://github.com/Automattic/vip-go-mu-plugins/blob/ae0dbabcee7eadd7d3e94c60dde756dcd0a26705/files/class-api-client.php#L230-L239

**Comment by andyjdavis** [comment]
Here is a pull request that resolves this :) https://github.com/Automattic/vip-go-mu-plugins/pull/2029

**Comment by andyjdavis** [comment]
That PR has been merged and I believe this issue is now resolved. I don't appear to have the power to close issues (which is probably correct) but I believe it can now be closed.

**Comment by trepmal** [comment]
resolved in #2029
