### ISSUE TITLE
Language upgrades not working when not on VIP GO ENV

### ISSUE THREAD

**Issue by jenkoian** [Automattic/vip-go-mu-plugins#1305]
When you attempt to update translations locally (to commit and push up to a VIP GO repo) it fails. 

---

## Expected/Desired Behavior

Click update translations on the updates page in admin and the translations successfully update.

## Actual Behavior

When you click update translations update actually fails with an error `Could not create directory.`.

## (Optional) Additional notes

If you see https://github.com/Automattic/vip-go-mu-plugins/blob/master/files/class-wp-filesystem-vip.php#L45-L50 it seems that when updating translations neither `wp_installing()` is true nor `get_option( 'core_updater.lock' )` and thus the update fails.

I can work around the issue by temporarily added a `return $this->direct;` but not ideal. Not sure if this is something that can be fixed here or as part of the core language upgrader?

**Comment by sjinks** [comment]
Fixed in #1377
