### ISSUE TITLE
Suggestion: Disable global terms by default on VIP Go

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/vip-go-mu-plugins#1308]
We have had problems with shared terms on some sites recently, although by default WordPress does not use them nowadays. The problem was basically that once a term was created, say <code>airplane</code>, in taxonomy <code>A</code>, another term created in taxonomy <code>B</code> with the same name (<code>airplane</code>) would get the same ID. Also, in the process, some database errors were thrown.

The database error, for instance, looks like this:

<blockquote>
  WordPress database error Duplicate entry 'M' for key 'PRIMARY' for query UPDATE <code>wp_terms</code> SET <code>term_id</code> = X WHERE <code>term_id</code> = Y made by global_terms
</blockquote>

I was able to find the source of this issue: The <code>global_terms()</code> function in <a href="https://core.trac.wordpress.org/browser/trunk/src/wp-includes/ms-functions.php#L1876">ms-functions.php</a>. This function would be executed on creation of a term, via the <code>term_id_filter</code> filter, by default set up.   Eventually, this filter would replace the ID of the term to a shared global ID found in the database (but this applies only for an already existing term, of course). <code>global_terms()</code> can be disabled completely, which seems to be the case with sites I checked. In the cases I checked, it was done via the database, by setting the meta-key <code>global_terms_enabled</code> to <code>0</code> in the <code>wp_sitemeta</code> table. <em>However</em>,  on the problematic sites, it was set to <code>1</code> -- and thus <code>global_terms()</code> did what it was designed to do.

In the cases I observed, this setting most likely came via import, from the previous setup of the site. We can assume to have more sites imported with this setting like this in the future, and to avoid problems like this, I would like to make the following suggestions:

a) We disable <code>global_terms</code> by default via code that we put in place on all VIP Go sites (see example code below).
b) We make sure that on importing sites, the <code>global_terms_enabled</code> setting in <code>wp_sitemeta</code> is set to <code>0</code>.
c) We alert administrator level users in <code>wp-admin</code> that <code>global_terms</code> is turned on, but don't actually disable it.

**Comment by gudmdharalds** [comment]
Gist is currently broken, so here is the patch for option a)

```
<?php

/*
 * Disable global terms on the site
 * as it creates problems with taxonomy
 * terms that share slugs. 
 */
add_filter( 'global_terms_enabled', '__return_false' );
```

**Comment by rinatkhaziev** [comment]
@gudmdharalds do you think this is still relevant?

**Comment by gudmdharalds** [comment]
>  do you think this is still relevant?

Judging the WordPress core code, I suspect that this could still happen in principle. However, I'm not aware of this being a problem for some years. On the basis of that this can probably be closed, but revisited if it becomes a problem.

**Comment by GaryJones** [comment]
@katag9k has got a current ticket related to this.
