### ISSUE TITLE
Request: Update Query Monitor from 3.1.1

### ISSUE THREAD

**Issue by GaryJones** [Automattic/vip-go-mu-plugins#1312]
## Expected/Desired Behavior

The used version of Query Monitor is 3.1.1, but the latest release is 3.3.7, which means everyone is missing out on some useful new features and bug fixes.

https://github.com/johnbillion/query-monitor/releases

**Comment by GaryJones** [comment]
The latest is now 3.5.2.

**Comment by chrean** [comment]
Being tracked on our internal Jira instance.

**Comment by rinatkhaziev** [comment]
This is addressed.
