### ISSUE TITLE
Make wpcom_vip_count_user_posts() more flexible

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/vip-go-mu-plugins#1315]
Location: https://github.com/Automattic/vip-go-mu-plugins/blob/f79d15aa5ec2dc0f60b8b68dcd65376fd071a18d/vip-helpers/vip-caching.php#L344-L366

This is a wrapper function around `count_user_posts()`, but it only allows for the default arguments. It would be useful if it were possible to pass in the additional arguments (namely post type), and have the cache key dynamic. You can see the allowed args here: https://github.com/WordPress/WordPress/blob/cff445d55f9bd53b608d3b9247ef62129aa9a816/wp-includes/user.php#L375-L395

**Comment by rinatkhaziev** [comment]
closing as Wontfix, but if this ever comes up again we can re-visit.
