### ISSUE TITLE
Srcset Ignoring Cropping

### ISSUE THREAD

**Issue by douglas-johnson** [Automattic/vip-go-mu-plugins#1319]
## Expected/Desired Behavior

I have these sizes set:
```
+-----------------+-------+--------+------+-------+
| name            | width | height | crop | ratio |
+-----------------+-------+--------+------+-------+
| full            |       |        | N/A  | N/A   |
| sc_portrait_lg  | 1080  | 1440   | hard | 3:4   |
| sc_landscape_lg | 1080  | 720    | hard | 3:2   |
| sc_portrait_md  | 720   | 960    | hard | 3:4   |
| sc_landscape_md | 720   | 480    | hard | 3:2   |
| sc_portrait_sm  | 360   | 480    | hard | 3:4   |
| sc_landscape_sm | 360   | 240    | hard | 3:2   |
+-----------------+-------+--------+------+-------+
```

When I use the `sc_portrait_md` size on an image that was uploaded at another aspect ratio, I expect to see the _sm and _lg sizes in the srcset with the cropping still enforced.

## Actual Behavior

All the images in the srcset that were not produced by the multipliers in Jetpack are using only the `w` argument instead of `resize`.

## Steps to Reproduce the Problem

As suggested in the VIP Go documentation, I wrote my own srcset to handle this in the short term. So if you're looking into this, reply and I'll turn that off so you can see the problem.

- Go to https://shopcatalog-com.go-vip.net/shop/
- Reduce the screen size to anything less than 720px
- The image will switch from portrait to its originally uploaded landscape aspect ratio.

## (Optional) Additional notes

I started a ticket with VIP support:
https://wordpressvip.zendesk.com/hc/en-us/requests/98027

I was referred to the documentation and I tried everything I could find there. If I'm just doing something wrong in my config or theme setup, that would be great news since its easy to fix.

My vip-config includes `define( 'WPCOM_VIP_USE_JETPACK_PHOTON', true );` and I tried adding a filter on `vip_go_srcset_enabled` but that seems to be true by default so the filter was unnecessary.

**Comment by mikeyarce** [comment]
Looking into this, it looks like WordPress Core is what makes the decision as to what image_sizes to include in the `srcset`:
https://github.com/WordPress/WordPress/blob/d9954ed4cb861dd54881c6484991ab5cf8d9c246/wp-includes/media.php#L653

The `srcset` attribute is meant to include images of the same aspect ratio for different screen resolutions, so it is expected that an image with a different aspect ratio would not be present in the `srcset`.

If you want to display different images of aspect ratios, you would need to customize your own image `srcset` or even better use the `picture` element with a custom `srcset`.

**Comment by douglas-johnson** [comment]
I don't think this issue should be closed. I responded in more detail in the related Zendesk ticket, but essentially WordPress Core is making the right decision and Jetpack is breaking it afterward.

The sizes delivered to Jetpack are correct, but Jetpack is modifying them incorrectly to use `w=` instead of `resize=`.

**Comment by mikeyarce** [comment]
This problem is only happening when Photon and the VIP Go srcset implementation are both used, so disabling Photon should be the right way to address this issue.
