### ISSUE TITLE
Make `wpcom_vip_include_active_plugins()` more defensive.

### ISSUE THREAD

**Issue by brettshumaker** [Automattic/vip-go-mu-plugins#1323]
## Desired Behavior

When fetching the `wpcom_vip_active_plugins` option value, we're assuming that the return value will be iterable when it actually may not be.

## Actual Behavior

If a non-iterable value is returned (either through an incorrect value being set or some other unknown error), the `foreach` will throw a warning.

## Steps to Reproduce the Problem

1. Set the value of `wpcom_vip_active_plugins` to a non-iterable value.
1. Load any WordPress page and observe the error being thrown.

**Comment by rebeccahum** [comment]
I think this has been resolved now: https://github.com/Automattic/vip-go-mu-plugins/blob/fdd99cf535e55eeda46d7a11a4cbb1603d8bc666/vip-plugins/vip-plugins.php#L279-L281
