### ISSUE TITLE
Disable Feature Hints

### ISSUE THREAD

**Issue by dartiss** [Automattic/vip-go-mu-plugins#1333]
As per a discussion with @jeherve at https://a8c.slack.com/archives/CBG1CP4EN/p1571740982220600, it would make sense to disable Feature Hints for all VIP Go clients.

This would require [the code here ](https://jetpack.com/support/feature-hints/#disabling-feature-hints)to be added to `vip-jetpack.php`.

Why? Because although we disable the use of plugin search, the featured hints part of this is still active and can fail, cause errors, etc. It just makes sense to therefore switch this off as well.

**Comment by mjangda** [comment]
That sounds like something that should be fixed upstream in Jetpack? (If things are actively breaking, then we should definitely deploy Gary's fix.)

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/jetpack/pull/14108

**Comment by GaryJones** [comment]
Closing to defer to upstream fix.
