### ISSUE TITLE
[lastpostmodified] Need to prevent override from returning a zero'd timestamp

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-go-mu-plugins#1356]
https://github.com/Automattic/vip-go-mu-plugins/blob/89b258d45f621dec7356a4867dbf2a6ed025e257/performance/lastpostmodified.php#L38

In one instance, this returned a `0000-00-00 00:00:00` timestamp (unknown cause). We should prevent that from happening, either here or when the value is saved. 

When the timestamp is zero'd, [WP will end up returning a 304](https://github.com/WordPress/WordPress/blob/1f816ad18d2f8384858604f382fc3d2898360a6a/wp-includes/class-wp.php#L472) for feeds to Varnish’s request for content, even though there are no conditional headers present in the request. This is an RFC violation and results in the error `304 response but not conditional fetch` in Varnish, resulting in a 503 being sent to the client even though the site is up and running.

**Comment by simonwheatley** [comment]
Noted in JIRA as [GH-3339]
