### ISSUE TITLE
Normalize client MU plugins URL for Windows OS

### ISSUE THREAD

**Issue by andrewfleming** [Automattic/vip-go-mu-plugins#1361]
## Expected/Desired Behavior

Fill with either one:

The `wpcom_vip_filter_client_mu_plugins_url()` function to produce a working URL when running in Windows environments
 https://github.com/Automattic/vip-go-mu-plugins/blob/6afb52132faeea78607b98b87abfca20ca334a9c/z-client-mu-plugins.php#L89

## Actual Behavior

The URLs are malformed and incorrect on Windows.

## Steps to Reproduce the Problem

Set up a local development environment running WordPress on a Windows/Apache/MySQL/PHP stack. 

Clone your VIP repo and the VIP MU Plugins repo as per [VIP Go local development](https://wpvip.com/documentation/vip-go/local-vip-go-development-environment/)

Browse to site and errors are encountered due to incorrect client MU plugins URL.

## (Optional) Additional notes

First reported and more detail provided here https://wp.me/pb3FO4-4T

Using Docker in Windows environment presents additional installation bugs and workarounds so WAMP stack seen as preferable.

**Comment by simonwheatley** [comment]
Noted in JIRA as [GH-3343]

**Comment by mjangda** [comment]
We don't support running these mu-plugins in a Windows environment so going to close this.
