### ISSUE TITLE
Jetpack: Mandatory "manage" module causing errors

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/vip-go-mu-plugins#1368]
We require the `manage` module here: https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-jetpack/jetpack-mandatory.php#L20

Jetpack then tries to load this module here: https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L1862

But there is no `modules/manage.php` file, so you end up with a PHP error:

> PHP Warning:  include_once(): Failed opening '/wp-content/mu-plugins/jetpack/modules/manage.php' for inclusion (include_path='.') in /wp-content/mu-plugins/jetpack/class.jetpack.php on line 1860

Looks like manage is no longer a module, so we should just remove this entry: https://github.com/Automattic/jetpack/pull/9089

**Comment by simonwheatley** [comment]
Noted in JIRA as [GH-3344]

**Comment by WPprodigy** [comment]
Just noting that the `manage.php` file was removed here: https://github.com/Automattic/jetpack/pull/13374
