### ISSUE TITLE
Export Personal Data broken

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/vip-go-mu-plugins#1399]
## Expected/Desired Behavior

Hitting "Download Personal Data" in the Export Personal Data page of wp-admin returns a download of the data.

## Actual Behavior

Hitting "Download Personal Data" in the Export Personal Data page of wp-admin results in the error message:

```
An error occurred while attempting to export personal data.

Unable to generate export file (archive) for writing: Unable to add data to export file.
```

It doesn't matter whether Zip extension is enabled or not, it seems that the file is not being uploaded properly and fails at this point if Zip is enabled: https://github.com/Automattic/vip-go-mu-plugins/blob/738371872a33f879212f20af35d244971bfdd975/001-core/privacy.php#L264

or at this point if Zip is not enabled: https://github.com/Automattic/vip-go-mu-plugins/blob/738371872a33f879212f20af35d244971bfdd975/001-core/privacy.php#L289

## Steps to Reproduce the Problem

1. Go to /wp-admin/tools.php?page=export_personal_data
1. If there are no data export requesters yet, add yourself as one via:
<img width="555" alt="Screen Shot 2020-01-10 at 4 29 22 PM" src="https://user-images.githubusercontent.com/16962021/72193369-60469100-33c6-11ea-801e-9b3377acbf8e.png">

3. Hit "Download Personal Data"

**Comment by GaryJones** [comment]
Debugging has started on this. At this point, it seems like PHP's ZipArchive can't handle a zip being created with a file stream wrapper as the reference.
