### ISSUE TITLE
Support symlinks in `wpcom_vip_include_plugin` by using `wp_register_plugin_realpath`

### ISSUE THREAD

**Issue by curtisbelt** [Automattic/vip-go-mu-plugins#1400]
## Desired Behavior

For plugins loaded via `wpcom_vip_include_plugin`, I'd like support for symlinks when using `plugin_basename()` or functions that depend upon it.

A common usecase is `plugins_url( 'script.js', __FILE__ );`. This was addressed in https://core.trac.wordpress.org/ticket/16953 by providing a function `wp_register_plugin_realpath` which allows WordPress to resolve symlinked paths in `plugin_basename`.

## Actual Behavior

`wp_register_plugin_realpath` is not used in `wpcom_vip_include_plugin`

## Steps to Reproduce the Problem

1. Load plugin via `wpcom_vip_include_plugin`
2. Observe it's not registered in the global `$wp_plugin_paths` and therefore symlinks cannot be resolved.

**Comment by mjangda** [comment]
Did you mean `wpcom_vip_load_plugin` instead of `_wpcom_vip_include_plugin`? The latter is an internal function not meant to be used directly.

**Comment by CurtisBelt** [comment]
@mjangda Yeah, the actual code change takes place in `_wpcom_vip_include_plugin` but you're right it makes more sense to refer to the public function in the issue :+1: Updating.

**Comment by curtisbelt** [comment]
PR was merged, closing
https://github.com/Automattic/vip-go-mu-plugins/pull/1401
