### ISSUE TITLE
Set a default VIP_GO_APP_ENVIRONMENT

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/vip-go-mu-plugins#1409]
We recommend clients use `VIP_GO_APP_ENVIRONMENT` now instead of `VIP_GO_ENV`, but on local environments this constant will never be defined by default, despite what we say in the docs currently: https://wpvip.com/documentation/vip-go/vip-go-environments/#differentiating-environments-in-code

Let's set a default for this constant as well for easier development flows.

**Comment by WPprodigy** [comment]
Similar to https://github.com/Automattic/vip-go-mu-plugins/commit/7a727402014a29b791ebe99cf8f6e261b1da555f

**Comment by sjinks** [comment]
I think we now [define this constant for local environments](https://github.com/Automattic/vip-container-images/blob/master/dev-tools/wp-config-defaults.php#L71-L73).

**Comment by rebeccahum** [comment]
Correct:

```
╰─$ vip dev-env --slug es-site exec -- wp shell
wp> VIP_GO_APP_ENVIRONMENT;
=> string(5) "local"
```
