### ISSUE TITLE
In class-vip-filesystem-stream-wrapper.php#L755 `$stats` seems to be undefined

### ISSUE THREAD

**Issue by itowhid06** [Automattic/vip-go-mu-plugins#1552]
In https://github.com/Automattic/vip-go-mu-plugins/blob/master/files/class-vip-filesystem-stream-wrapper.php#L755 `$stats` seems to be undefined

**Comment by hanifn** [comment]
@itowhid06 Nice catch! Thanks for pointing this is out. Fix is on the way
