### ISSUE TITLE
Liveblog - redirect all frontend liveblog pages to the https version if user has posting capabilities

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#158]
Since _all_ Go wp-admins go over HTTPS, we need to match that protocol from the frontend when uploading images from liveblog, otherwise the ajax request fails.

Maybe this should be part of liveblog, though that would require the correct protocol being set for the site url, which is not always the case on go.

**Comment by philipjohn** [comment]
Sorry, I've only just seen this. I can't see that Liveblog is picky anywhere, so it's probably already grabbing that from site_url() anyway.

**Comment by simonwheatley** [comment]
If LiveBlog sees `FORCE_ADMIN_SSL` is truthy, perhaps it could use an HTTPS URL for images and posting, @philipjohn?

**Comment by philipjohn** [comment]
That sounds reasonable, yeah. Want to open an issue on the Liveblog GH and we'll get it added?

**Comment by rebeccahum** [comment]
This would better live in the [Liveblog GH repo](https://github.com/Automattic/liveblog/issues).
