### ISSUE TITLE
YouTube oEmbed Handlers

### ISSUE THREAD

**Issue by whyisjake** [Automattic/vip-go-mu-plugins#1604]
On WordPress.com, the YouTube oEmbed handler adds a class to the iframe that is missing on VIP Go. I'm wondering if we should copy this behavior to ensure smoother migrations for clients moving the platform.

## Expected/Desired Behavior

Fill with either one:

1. Expected behavior for bugs
1. Desired behavior for improvements/enhancements

### WordPress.com

```
<iframe class="youtube-player" width="640" height="360" src="https://www.youtube.com/embed/ZbtOGhaG1P8?version=3&amp;rel=1&amp;fs=1&amp;autohide=2&amp;showsearch=0&amp;showinfo=1&amp;iv_load_policy=1&amp;wmode=transparent" allowfullscreen="true" style="border:0;"></iframe>
```

### VIP Go

```
<iframe title="Introducing RR1" width="500" height="281" src="https://www.youtube.com/embed/ZbtOGhaG1P8?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
```

## Steps to Reproduce the Problem

1. Add a YouTube video to a classic editor post on its own line.
1. Preview post

## Additional notes

Any other relevant information to help with debugging/implementation.

This code was taken from a VIP client and shared with PMC. It adds the title attribute, but could be extended for class names.

```
<?php
/**
 * Add title attribute to YouTube iframe.
 *
 * @param string $content The content.
 *
 * @return string
 */
function pmc_add_youtube_iframe_title( $content ) {
	if ( false !== strpos( $content, 'youtube-player' ) ) {
		$youtube_player_title = __( 'YouTube Video Player', 'pmc' );
		$content              = str_replace(
			array(
				"class='youtube-player'",
				'class="youtube-player"',
			),
			array(
				"class='youtube-player' title='" . esc_attr( $youtube_player_title ) . "'",
				'class="youtube-player" title="' . esc_attr( $youtube_player_title ) . '"',
			),
			$content
		);
	}
	return $content;
}
add_filter( 'the_content', 'pmc_add_youtube_iframe_title', 11 );
```

**Comment by mjangda** [comment]
If this is for migrations, it should go in the company plugin.
