### ISSUE TITLE
Plugin and theme updates should be seen but no action presented

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#162]
Currently if there are plugin or theme updates the user is presented with an "update plugins" or "update themes" button. 

We seem to be setting [`DISALLOW_FILE_MODS`](https://codex.wordpress.org/Editing_wp-config.php#Disable_the_Plugin_and_Theme_Editor) here: https://github.com/Automattic/vipd/blob/master/templates/wp-config#L8

![screen shot 2016-03-22 at 9 06 29 am](https://cloud.githubusercontent.com/assets/233434/13952725/dfb03f10-f02f-11e5-9a0d-f0fcb2bcf895.png)

Is this some core behaviour we need to change?

**Comment by rebeccahum** [comment]
Looks like it's been fixed:
<img width="1241" alt="Screen Shot 2022-08-05 at 12 40 36 PM" src="https://user-images.githubusercontent.com/16962021/183141034-49db0e11-6774-42c3-ac9c-367b3f542f75.png">

Closing.
