### ISSUE TITLE
Support client mu-plugins

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#166]
- Mount mu-plugins as `vip-mu-plugins` or something less confusing.
- Include all PHP files in this directory on `muplugins_loaded`

https://github.com/WordPress/WordPress/blob/703d5bdc8deb17781e9c6d8f0dd7e2c6b6353885/wp-settings.php#L210-L223

Can we do this without breaking the `muplugins_loaded` hook? How early is `add_action` available? Can we add a hook before mu-plugins are loaded and include them there?

**Comment by mjangda** [comment]
Possible simpler option:

- Add a `client-mu-plugins` folder (or something similar to `vip-skeleton`).
- Add whatever to `vipd` to make sure that folder ^^ gets included in containers.
- Add a `zzz-client-mu-plugins.php` that just loads files from `client-mu-plugins the same way `wp_get_mu_plugins` does.

The trade-off is that client mu-plugins load later (although, still before `muplugins_loaded`) but I think that's okay.

**Comment by joshbetz** [comment]
We could probably even call it `mu-plugins` in the vip-skeleton repo and map it as client-mu-plugins in the container, although that may be too confusing.
