### ISSUE TITLE
Query Monitor missing files on new VIP Go local installs

### ISSUE THREAD

**Issue by douglas-johnson** [Automattic/vip-go-mu-plugins#1684]
## Expected/Desired Behavior

Access Query Monitor while logged in to local environment.

## Actual Behavior

Either Query Monitor has no output ( admin ) or a critical error is thrown ( front-end ).

The error is complaining about the missing file `mu-plugins/query-monitor/output/Headers.php`

That file is not checked in to this repo as of #1683 when the submodule was removed in favor of checking in the files. 

You can see that there's no output folder on master here: https://github.com/Automattic/vip-go-mu-plugins/tree/master/query-monitor

## Steps to Reproduce the Problem

1. Start a new VIP Go local environment
1. Log in to WP Admin
1. Try to open Query Monitor

## (Optional) Additional notes

I was able to fix this locally by replacing the `mu-plugins/query-monitor` folder with a freshly downloaded copy of Query Monitor version 3.1.1 from WordPress.org

https://wordpress.org/plugins/query-monitor/advanced/

On old installs that previously used the submodule version of Query Monitor, no file changes where shown in the local git repository.

**Comment by GaryJones** [comment]
Would a `git pull` in the `mu-plugins` directory likely have had the same effect?

**Comment by douglas-johnson** [comment]
@GaryJones `git pull` in the `mu-plugins` directory did not work for me. I just tried on an existing local installation and the `mu-plugins/query-monitor/output` directory is still missing.

**Comment by GaryJones** [comment]
Thanks for reporting, @douglas-johnson - great catch!
