### ISSUE TITLE
Automattic\VIP\Search\Queue\Schema logging database errors on MySQL when preparing table

### ISSUE THREAD

**Issue by alecgeatches** [Automattic/vip-go-mu-plugins#1734]
## Expected/Desired Behavior

`Automattic\VIP\Search\Queue\Schema::_prepare_table()` completes in the background without database errors.

## Actual Behavior

When `Automattic\VIP\Search\Queue\Schema::_prepare_table()` runs, I'm seeing this error:

```
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL
server version for the right syntax to use near
'IF EXISTS `unique_object_and_status` on wp_vip_search_index_queue' at line 1 for query 
DROP INDEX IF EXISTS `unique_object_and_status` on wp_vip_search_index_queue made by shutdown_action_hook,
do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters,
Automattic\VIP\Search\Queue\Schema->maybe_create_table_on_shutdown,
Automattic\VIP\Search\Queue\Schema->prepare_table,
Automattic\VIP\Search\Queue\Schema->_prepare_table
```

The error seems to originate from this code:

https://github.com/Automattic/vip-go-mu-plugins/blob/f1d7c4ad03698573afa9f5a94edbc03db6e7210d/search/includes/classes/queue/class-schema.php#L144-L146

As far as I can tell, the `IF EXISTS` part of `DROP INDEX IF EXISTS` is not [valid MySQL syntax](https://dev.mysql.com/doc/refman/5.7/en/drop-index.html) which is causing the error. It's probably also the case that this code is not removing the old index as expected.

## Steps to Reproduce the Problem

I'm experiencing these problems while provisioning a local WordPress instance with `vip-go-mu-plugins` installed, and it can also happen later when the `vip_search_queue_db_version` transient expires. An easier way to force the code to run is to delete the transient manually and call `prepare_table()`:

```bash
$ wp eval "delete_transient('vip_search_queue_db_version'); \$schema = new Automattic\VIP\Search\Queue\Schema; \$schema->prepare_table();"

[25-Aug-2020 19:38:04 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS `unique_object_and_status` on wp_vip_search_index_queue' at line 1 for query DROP INDEX IF EXISTS `unique_object_and_status` on wp_vip_search_index_queue made by require_once('/root/.composer/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->do_early_invoke, WP_CLI\Runner->run_command_and_exit, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, Eval_Command->__invoke, eval, Automattic\VIP\Search\Queue\Schema->prepare_table, Automattic\VIP\Search\Queue\Schema->_prepare_table
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;IF EXISTS `unique_object_and_status` on wp_vip_search_index_queue&#039; at line 1]<br /><code>DROP INDEX IF EXISTS `unique_object_and_status` on wp_vip_search_index_queue</code></p></div>
```

**Comment by nickdaugherty** [comment]
Thanks for the report @alecgeatches - on VIP we use MariaDB, which supports `DROP INDEX IF EXISTS` as of 10.1.4. We'll have to come up with a workaround for environments not running that db server.

**Comment by alecgeatches** [comment]
@nickdaugherty Thank you for the information. I can update my local environment to use MariaDB as well and this should no longer be a problem for me personally. Thanks!

**Comment by sjinks** [comment]
Closing, as the `DROP INDEX IF EXISTS` is no longer in the codebase.
