### ISSUE TITLE
Support User password not being set correctly

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#176]
Currently the password being set in the admin console does not work in the WordPress site.

**Comment by joshbetz** [comment]
I thought I mentioned this somewhere else, but we've had problems with this in the shell script module previously https://github.com/Automattic/vipd/blob/cedcbb9ffa665cf2b39c9d7fd24b341ef96c9d7f/modules/shell-script.php

**Comment by nickdaugherty** [comment]
This has been fixed in https://github.com/Automattic/vipd/pull/244
