### ISSUE TITLE
Possibly port over recent Memcached plugin changes

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#178]
See: https://plugins.trac.wordpress.org/log/memcached

**Comment by nickdaugherty** [comment]
Still need to do this, but using the GH version as the source (has some whitespace / code style changes not synced).

https://github.com/Automattic/wp-memcached

**Comment by GaryJones** [comment]
Based on https://github.com/Automattic/vip-go-mu-plugins/pull/2327 then I think this can be closed?
