### ISSUE TITLE
wpcom_intermediate_sizes should return an empty array

### ISSUE THREAD

**Issue by emrikol** [Automattic/vip-go-mu-plugins#180]
Currently `wpcom_intermediate_sizes()` returns `null`, causing issues with code using `get_intermediate_image_sizes()`, which should be an `array()`:

Example: `Warning:  Invalid argument supplied for foreach() in /chroot/var/www/wp-admin/includes/image.php on line 93`

I think all it needs is a `return` added to [line 597](https://github.com/Automattic/vip-go-mu-plugins/blob/master/a8c-files.php#L597) of [a8c-files.php](https://github.com/Automattic/vip-go-mu-plugins/blob/master/a8c-files.php)

```
function wpcom_intermediate_sizes( $sizes ) {
    return __return_empty_array();
}
```

**Comment by joshbetz** [comment]
Fixed in https://github.com/Automattic/vip-go-mu-plugins/commit/1c5eb1c9d92d89297bf7130431ed3e00e415355e
