### ISSUE TITLE
Carousel/slideshow stylesheets don't have namespaced classes

### ISSUE THREAD

**Issue by bjorn2404** [Automattic/vip-go-mu-plugins#1837]
## Expected Behavior

I expect the styling classes in Jetpack to be namespaced and not conflict with common class naming.

## Actual Behavior

The carousel stylesheets ([slideshow-shortcode.css](https://github.com/Automattic/vip-go-mu-plugins/blob/master/jetpack-9.0/modules/shortcodes/css/slideshow-shortcode.css) and [slideshow-shortcode-rtl.css](https://github.com/Automattic/vip-go-mu-plugins/blob/master/jetpack-9.0/modules/shortcodes/css/slideshow-shortcode-rtl.css)) don't have "jetpack" prefixed to all the classes whereas the other files in [the same directory](https://github.com/Automattic/vip-go-mu-plugins/tree/master/jetpack-9.0/modules/shortcodes/css) do. For example, in the recipes.css file classes look like `.jetpack-recipe` and in in the quiz.css file they look like `div.jetpack-quiz` but in the slideshow files they look like `.slideshow-loading`.

## Steps to Reproduce the Problem

These class names seem too common to me and created an issue on a project I'm working on where a carousel is picking up styling from the above Jetpack files that it shouldn't.

**Comment by GaryJones** [comment]
Since this would seem to stem from upstream, could you please raise this issue there?

https://github.com/Automattic/jetpack/issues

**Comment by bjorn2404** [comment]
Of course, that makes sense.
