### ISSUE TITLE
Deprecated instagram_cache_oembed_api_response_body hook in vip-caching.php

### ISSUE THREAD

**Issue by gmazzap** [Automattic/vip-go-mu-plugins#1859]
## Expected Behavior

No deprecated notices.

## Actual Behavior

Deprecated notice shown:

> Deprecated: instagram_cache_oembed_api_response_body used for __return_true is deprecated since version with no alternative available. in /var/www/wp-includes/functions.php on line 4784

## Steps to Reproduce the Problem

1. Ensures WP_DEBUG is true
2. Ensure VIP GO MU plugins are installed
3. Ensure JetPack 9.1 is installed
4. Open any website page in browser

Note: 1 to 3 are true in any current VIP GO environment right now.

## Proposed solution

Remove this line: https://github.com/Automattic/vip-go-mu-plugins/blob/ac59632bb576b7962fc27e2cfaa46342c0393d3c/vip-helpers/vip-caching.php#L774

**Comment by nickdaugherty** [comment]
Thanks for the report @gmazzap - we've triaged this internally and will have a look.

**Comment by GaryJones** [comment]
Fixed in #1873.
