### ISSUE TITLE
Deployment to Automattic/vip-mu-plugins-public broken

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#194]
Deployment to `Automattic/vip-mu-plugins-public` was broken when this repo became public.

Error:

```
$ ./ci/prepare.sh
+mkdir -p /home/travis/.ssh
+ssh-add -D
Could not open a connection to your authentication agent.
The command "./ci/prepare.sh" failed and exited with 2 during .
```

There's also a strong possibility that some code can be removed from the `prepare.sh` and perhaps `deploy.sh` scripts.

**Comment by joshbetz** [comment]
Can we just delete the `Automattic/vip-mu-plugins-public` repo?

**Comment by simonwheatley** [comment]
@davidbinovec asked the same question. Two considerations:

* Clients with existing local development repos (although we could add a notice to admin area and log a doing it wrong to notify them)
* I'm wary that this repo uses submodules, which can be a little trick to master

I am leaning more towards deleting it currently.

**Comment by ethitter** [comment]
Let's update Go Quickstart, delete the outdated mirror, and publish a lobby post about it. The longer it hangs around, the more irrelevant it becomes, and there aren't a lot of good reasons to fix the synching (in my opinion, at least).

**Comment by mjangda** [comment]
Seems to be fine now. I like using it for merging over to our deploy repo since it deals with submodules and such.
