### ISSUE TITLE
object-cache.php references WPMU_PLUGIN_DIR which isn't yet defined

### ISSUE THREAD

**Issue by kasparsd** [Automattic/vip-go-mu-plugins#2077]
## Expected/Desired Behavior

1. The `object-cache.php` bundled with this repository can be used in local development environment.

## Actual Behavior

WordPress loads `drop-ins/object-cache.php` (which has been symlinked to `wp-content/object-cache.php`) and returns the following error:

```
PHP Warning:  Use of undefined constant WPMU_PLUGIN_DIR - assumed 'WPMU_PLUGIN_DIR' (this will throw an Error in a future version of PHP) in /var/www/html/wp-content/plugins/vendor/automattic/vip-go-mu-plugins/drop-ins/object-cache.php on line 4
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP Stack trace:
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP   1. {main}() /var/www/html/wp/index.php:0
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP   2. require() /var/www/html/wp/index.php:17
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP   3. require_once() /var/www/html/wp/wp-blog-header.php:13
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP   4. require_once() /var/www/html/wp/wp-load.php:49
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP   5. require_once() /var/www/html/wp-config.php:57
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP   6. wp_start_object_cache() /var/www/html/wp/wp-settings.php:131
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP   7. require_once() /var/www/html/wp/wp-includes/load.php:666
vipgo_1        | [21-Apr-2021 11:09:38 UTC] PHP Warning:  require_once(WPMU_PLUGIN_DIR/lib/class-apc-cache-interceptor.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/vendor/automattic/vip-go-mu-plugins/drop-ins/object-cache.php on line 4
```

because `WPMU_PLUGIN_DIR` is not yet defined when `wp-content/object-cache.php` is loaded by WP core in `wp-settings.php` [during `wp_start_object_cache()`](https://github.com/WordPress/WordPress/blob/f4f125b869b006cefff0c2d6e7291929fb3e16b5/wp-settings.php#L131).

The `WPMU_PLUGIN_DIR` constant is defined during `wp_plugin_directory_constants();` which is [called only _after_](https://github.com/WordPress/WordPress/blob/f4f125b869b006cefff0c2d6e7291929fb3e16b5/wp-settings.php#L320) `wp_start_object_cache()` in the same file.

## Steps to Reproduce the Problem

1. Symlink `drop-ins/object-cache.php` to `wp-content/object-cache.php` in your local development environment
1. Request any page, post or admin from WordPress.

**Comment by kopepasah** [comment]
@kasparsd we are not using symlinks, but rather [copying this file over during setup](https://github.com/rareview/wp-vip-site/blob/default/.local/bin/post-start.sh#L18), and have no issues.

Have you tried copying this over manually and, if so, do you still experience the errors?

**Comment by kasparsd** [comment]
Thanks for the suggestion @kopepasah! Could it be that you're manually defining `WPMU_PLUGIN_DIR` somewhere in `wp-config.php`? Because the issue comes from a core WP constant `WPMU_PLUGIN_DIR` not being defined when WP core loads the `object-cache.php` drop-in. So it shouldn't technically matter if `object-cache.php` is an actual file or a symlink.

The WP core sequence is like this:

1. WP calls `wp_start_object_cache()` in *line 131* of `wp-settings.php`
2. WP defines `WPMU_PLUGIN_DIR` in *line 320* of the same file when it calls `wp_plugin_directory_constants()`.

So the `WPMU_PLUGIN_DIR` shouldn't be available for `object-cache.php` unless you manually define it somewhere before the `wp_start_object_cache()` call.

I'm wondering if VIP is defining the constant super early somewhere at the platform config similar to how it is done for the tests here https://github.com/Automattic/vip-go-mu-plugins/blob/72ddfa265018fe56c8c3a634a0db6afe83baf06b/tests/bootstrap.php#L11

**Comment by kopepasah** [comment]
Oh yeah, that's definitely it, as defining early is something we have done. Needs to be fixed for sure. 

On a side note, I hope the fix is not to hardcode `WP_CONTENT_DIR . '/mu-plugins/` like it is done in [`lib/sunrise/sunrise.php`](https://github.com/Automattic/vip-go-mu-plugins/blob/master/lib/sunrise/sunrise.php#L12) (mentioned in #2358).

**Comment by rebeccahum** [comment]
Closing, should be fixed by https://github.com/Automattic/vip-go-mu-plugins/pull/3491.
