### ISSUE TITLE
Plugins with hotfixes

### ISSUE THREAD

**Issue by scottsweb** [Automattic/vip-go-mu-plugins#209]
Please track any plugins that have had hotfixes applied in this ticket. We will need to make sure things are kept in sync and that patches are sent upstream. 

cc @david-binda @emrikol @joshbetz @ethitter @simonwheatley @nickdaugherty @philipjohn

**Comment by scottsweb** [comment]
* [ ] Livefyre Apps

**Comment by mjangda** [comment]
Shared plugins are no more.
