### ISSUE TITLE
ep_autosuggest_placeholder queries are being sent to Elasticsearch server

### ISSUE THREAD

**Issue by petenelson** [Automattic/vip-go-mu-plugins#2163]
I have an Elasticsearch server setup locally and am running the latest VIP mu-plugins forked ElasticPress code. I was debugging some new code I was working on, and happened to notice the code that generates the JSON query for autosuggest was being sent to the Elasticsearch server each time I viewed a page on the site. This [code in generate_search_query()](https://github.com/Automattic/ElasticPress/blob/8e9c061e966aa3046f155a3375ae57a2d520d7e1/includes/classes/Feature/Autosuggest/Autosuggest.php#L443) turns off the HTTP remote request as it's only being used by ElasticPress to generate the query for localization on the frontend, and doesn't actually need to be run against Elasticsearch for results. This JSON query gets localized to `window.epas.query` object, and then [frontend javascript](https://github.com/Automattic/ElasticPress/blob/8e9c061e966aa3046f155a3375ae57a2d520d7e1/assets/js/autosuggest.js) can send this query to a `_search` endpoint to get results directly from Elasticsearch.

I was using ngrok as a proxy in order to inspect the queries I was working on when I happened to notice this autosuggest query being sent. It appears to be sent multiple times each time a page loads on the site.
![image](https://user-images.githubusercontent.com/1757075/119925862-db690280-bf3b-11eb-9d00-0690f348ea1e.png)

I believe this code is the culprit https://github.com/Automattic/vip-go-mu-plugins/blob/d1b30bf63279665e96976a5c9cc7531bb855693c/search/includes/classes/class-search.php#L414 and it may need a check to skip the remote request if it's just generating the query body and doesn't need the response. Commenting out that filter and refreshing a page on the site shows there are no remote requests to Elasticsearch being made.

While VIP Elasticsearch doesn't support autosuggest currently (it needs a publicly accessible Elasticsearch `_search` endpoint), we've implemented some workarounds to enable the Autosuggest code within VIP's forked ElasticPress code and use a custom WP REST endpoint to proxy the query to the VIP Elasticsearch server. This may not be a large issue currently, but could be in the future if VIP enables autosuggest on a larger scale to all clients.

**Comment by rinatkhaziev** [comment]
Hey Pete, 

So am I understanding correctly that this behavior is exhibited when you enable the Autosuggest feature on our fork?

**Comment by petenelson** [comment]
Correct. We're enabling autosuggest within the `ep_feature_settings` option, some snippets as our code is in a private repo.

```
$feature_settings = get_option( 'ep_feature_settings' );

$feature_settings['autosuggest'] = [
	'endpoint_url'         => '(this ends up being a local WP REST endpoint)',
	'autosuggest_selector' => '.ep-autosuggest-input',
	'trigger_ga_event'     => '0',
	'active'               => true,
	'force_inactive'       => false,
];

update_option( 'ep_feature_settings', $feature_settings );
```
