### ISSUE TITLE
Support loading plugins from theme/plugins

### ISSUE THREAD

**Issue by cfg** [Automattic/vip-go-mu-plugins#217]
For parity with WPCOM, `wpcom_vip_load_plugin()` should support `theme` as a special second parameter to load plugins from `theme-name/plugins`

From the original post https://lobby.vip.wordpress.com/2016/06/10/loading-plugins-from-your-theme/

> * In your theme you can now create a plugins folder: `theme-name/plugins`
> * Within that theme you can place the plugins you would like to use, e.g.; `theme-name/plugins/mce-table-buttons`
> * That plugin might include a wpcom-helper.php: `theme-name/plugins/mce-table-buttons/wpcom-helper.php`
> Now you can load that plugin with `wpcom_vip_load_plugin( 'mce-table-buttons', 'theme' );`
> 
> As you can see from the example above, the second parameter of `wpcom_vip_load_plugin()` now takes “theme” as a value. When this happens the function looks in the _currently active theme_ for a plugins folder containing a plugin with the name specified. As a fallback, it will also search the parent theme (where applicable) and the shared plugins repository.

**Comment by joshbetz** [comment]
We actually talked about doing this for VIP Go at the same time as WordPress.com VIP and decided against it because plugins should not be in the theme in VIP Go anyway. Since we have the ability to, plugins should be in plugins on VIP Go.
