### ISSUE TITLE
WordPress Import should import all post meta for menu items

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/vip-go-mu-plugins#219]
Currently, the Import plugin only imports certain post meta for the menu items. A plugin that I've written (Nav Menu roles) relies on post meta for the nav manu items and this meta is not being imported. So I'd like to suggest that that nav menu items import all their post meta. 

My code modification can be seen [here](https://plugins.trac.wordpress.org/ticket/1678)

**Comment by ethitter** [comment]
@helgatheviking, thanks for the report! While this repository includes the WordPress Importer, it isn't the official repo for that plugin. Instead, you can report your patch at https://wordpress.org/support/plugin/wordpress-importer, where the maintainers have a better chance of reviewing your contribution.

**Comment by helgatheviking** [comment]
I posted it there [3 years ago](https://wordpress.org/support/topic/failure-to-import-post-meta-for-nav-menu-item) and was told to try posting in trac. In trac it was suggested to post it here. I actually patched it (or did 3 years ago), but there's apparently no official place to post it.

**Comment by ethitter** [comment]
@helgatheviking - sorry for the confusion that arose from trac. This repo is simply another user of the Importer, but it has no further connection with that plugin. To the best of my knowledge, the support forum on WordPress.org is the only place to report issues with the importer.
