### ISSUE TITLE
wp-mediaelement styles are being loaded on all page views when using Jetpack 9.9

### ISSUE THREAD

**Issue by hrkhal** [Automattic/vip-go-mu-plugins#2301]
We've spotted that the wp-medialement styles are being loaded on all page views.  This regression was introduced in Jetpack 9.9

The styles are coming from the `Podcast_Player` extension regardless of whether the relevant block is used on page or not.

`/wp-includes/js/mediaelement/mediaelementplayer-legacy.min.css?ver=4.2.16`
`/wp-includes/js/mediaelement/wp-mediaelement.min.css?ver=5.7.2`

This is the offending line: 

https://github.com/Automattic/vip-go-mu-plugins/blob/68f5b67024424a34724652d2dc96a6c602a3ea9f/jetpack-9.9/extensions/blocks/podcast-player/podcast-player.php#L54

https://github.com/Automattic/jetpack/commit/cf8864a43ec2e2e740d166992c5a74d9e9aaadf7#r53737068

Commenting out the offending line prevents the styles from being loaded.

We'll be fixing the issue in the mean time by removing the init action for the `Podcast_Player`:
```remove_action( 'init', '\Automattic\Jetpack\Extensions\Podcast_Player\register_block' );```

**Comment by mikeyarce** [comment]
Added this issue to Jetpack here: https://github.com/Automattic/jetpack/issues/20437

**Comment by mwordpress** [comment]
@hrkhal thanks but this work for me without backslash in start

`remove_action( 'init', 'Automattic\Jetpack\Extensions\Podcast_Player\register_block' );`

**Comment by rebeccahum** [comment]
Closing since this is a Jetpack issue.
