### ISSUE TITLE
Use defined WPMU_PLUGIN_DIR constant for Must Use plugins directory.

### ISSUE THREAD

**Issue by kopepasah** [Automattic/vip-go-mu-plugins#2358]
Currently, the `lib/sunrise/sunrise.php` drop-in references the `WP_CONTENT_DIR` constant for requiring the `lib/utils/context.php`, but calling the Must Use plugins directory in this way does not respect the `WPMU_PLUGIN_DIR` defined constant.

It must also be noted, that this is not the only area where the `WPMU_PLUGIN_DIR` is not utilized, so perhaps those need to be changed as well.

Happy to make these changes and submit a pull request, if the team desires.

**Comment by rinatkhaziev** [comment]
@kopepasah thanks for bringing that up. 

WPMU_PLUGIN_DIR is not defined at the moment of inclusion of the sunrise code if you look at the core bootstrap code:

https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L137-L144 - is where the sunrise code is loaded.
https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L334 - is where the constant gets defined. 

I did a quick test to illustrate the point:

```
wp shell --allow-root --path=/var/www
/wp-content/mu-plugins/lib/sunrise/sunrise.php:5:
bool(false) // defined( 'WPMU_PLUGIN_DIR' );
WPMU_PLUGIN_DIRroot // exit( WPMU_PLUGIN_DIR );
```

**Comment by kopepasah** [comment]
@rinatkhaziev thanks for the feedback and while you are correct, it still does not use the correct `mu-plugins` directory when it is defined early. 

Best way to handle this would be to first check if it is defined and, if not, use the hardcoded version, otherwise use the defined version. 

Using the hardcoded version only does not respect when others define the `WPMU_PLUGIN_DIR` constant early, which causes unexpected results with VIP's MU Plugins.
