### ISSUE TITLE
Purge posts page

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#241]
If the site is using a different page to list posts, i.e. `page_for_posts`, we should purge that posts page URL.

**Comment by WPprodigy** [comment]
Just ran into this. Seems pretty straightforward and needed by all: https://github.com/Automattic/vip-go-mu-plugins/blob/da7fcd24b773e1957687c6eb56f0b56ddd402d9e/vip-cache-manager/vip-cache-manager.php#L281
