### ISSUE TITLE
2fa: Change placeholder phone number

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-go-mu-plugins#2433]
https://github.com/Automattic/vip-go-mu-plugins/blob/bb29dd028c771aec996b61a38aa7cc259f31e0a7/wpcom-vip-two-factor/sms-provider.php#L196

I might be the only person, but I was unfamiliar with this phone number easter egg. Additionally, the 415 area code made me think this might be a genuine a8c number.

I think it would be good to switch this to a more readily recognizable fake number (555...., 123..., or even ###...) so that no one will, like me, glance at this and think their 2fa codes might be going to an unknown party.

**Comment by GaryJones** [comment]
There are all sorts of issues here, such as a requirement to include country code numbers, and not using a placeholder that is US-specific.

https://uxmovement.com/forms/bad-practices-on-phone-number-form-fields/ has a good write-up, and https://uxplanet.org/phone-number-field-design-best-practices-23957cbd86d5 suggests include a country-code dropdown.

Maybe consider using https://github.com/jackocnr/intl-tel-input
