### ISSUE TITLE
Hardcode upload limit to 1GB

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#250]

**Comment by nickdaugherty** [comment]
Can you add some details about why this is needed / what this solves?

**Comment by joshbetz** [comment]
In multisite, the default upload limit is 1MB. There is a super admin option to customize it, but without control over Nginx configs, it's potentially very confusing. Setting the limit to 2GB in WordPress, for example, won't work.

**Comment by nickdaugherty** [comment]
Makes sense!
