### ISSUE TITLE
Add note to Purge Cache button for sandboxed sites.

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#255]
When a site is sandboxed, the purge cache button only purges the cache on the sandbox, no production cache nodes. We should add some kind of notice to avoid confusion.

**Comment by GaryJones** [comment]
I thought I watched a learnup video from @simonwheatley about caching, which said that clearing (at least some type of) sandbox caches DID clear production caches.

Simon, can you clarify please?

**Comment by mjangda** [comment]
> which I thought said that clearing (at least some type of) sandbox caches DID clear production caches.

You're probably thinking of memcached.

**Comment by mjangda** [comment]
We added some clarification in #962
