### ISSUE TITLE
Podcast block still loading mediaelement scripts everywhere

### ISSUE THREAD

**Issue by codetipi** [Automattic/vip-go-mu-plugins#2648]
## Expected/Desired Behavior

1. mediaelement should not load on every page

## Actual Behavior

mediaelement loads on every page

## Steps to Reproduce the Problem

1. Install Jetpack
2. Check frontend HTML to find wp-mediaelement and mediaelement scripts loading

## (Optional) Additional notes

This has been around since Jetpack 9.x

**Comment by rebeccahum** [comment]
Hi, if this issue is still applicable, please open this issue at https://github.com/Automattic/jetpack. Thanks!
