### ISSUE TITLE
Error after enabling objects-to-objects

### ISSUE THREAD

**Issue by ConnectedCat** [Automattic/vip-go-mu-plugins#265]
Notice:  wpcom_vip_enable_term_order_functionality is deprecated since version 2.0.0 with no alternative available. in /var/www/wp-includes/functions.php on line 3660

Fatal error:  Uncaught Error: Class 'Post_Selection_UI' not found in /var/www/wp-content/mu-plugins/shared-plugins/objects-to-objects/admin/admin.php:15
Stack trace:
#0 /var/www/wp-content/mu-plugins/shared-plugins/objects-to-objects/src/o2o.php(64): O2O_Admin->init()
#1 /var/www/wp-includes/plugin.php(525): O2O->init('')
#2 /var/www/wp-settings.php(393): do_action('init')
#3 /var/www/wp-config.php(57): require_once('/var/www/wp-set...')
#4 /var/www/wp-load.php(37): require_once('/var/www/wp-con...')
#5 /var/www/wp-admin/admin.php(31): require_once('/var/www/wp-loa...')
#6 {main}

  thrown in /var/www/wp-content/mu-plugins/shared-plugins/objects-to-objects/admin/admin.php on line 15

After enabling 'Objects to Objects' plugin in VIP Go install

**Comment by mjangda** [comment]
Plugin was removed from mu-plugins.
