### ISSUE TITLE
Exclude convenience domains from alloptions alerting

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-go-mu-plugins#2768]
https://github.com/Automattic/vip-go-mu-plugins/blob/5e7b43d955557385ba2614156bcd6b7238ea63ab/alloptions-limit.php#L126-L132

Convenience domains typically indicate an unlaunched site. We should remove the alerts sent to VIP to reduce noise.

**Comment by WPprodigy** [comment]
On the flip side though, could be good to know about it before a launch.
