### ISSUE TITLE
Issue with ES_WP_Query

### ISSUE THREAD

**Issue by jonathanstegall** [Automattic/vip-go-mu-plugins#2925]
## Expected/Desired Behavior

When I started testing Elasticsearch in preparation for migrating from Jetpack to Enterprise search, I noticed a difference in how WP_Query arguments are handled by es-wp-query.

With Jetpack, I can run queries through Jetpack with es-wp-query by adding `es` to the query arguments. Here's an example of such a query from my logs:

```zsh
[19-Feb-2022 03:07:12 UTC] args is Array
(
    [post_type] => message
    [post_status] => publish
    [orderby] => menu_order
    [posts_per_page] => -1
    [meta_query] => Array
        (
            [0] => Array
                (
                    [key] => _wp_inserted_message_region
                    [value] => article_bottom
                    [compare] => =
                )

        )

    [es] => 1
)
```

The result when I run this query is that it returns me the results ordered by the `menu_order` as is set in the editor.

## Actual Behavior

When I run this same query through Enterprise search (locally), it does not respect the `orderby` parameter. That is, posts are not sorted by `menu_order`. Reading the [es-wp-query readme](https://github.com/Automattic/vip-go-mu-plugins/blob/master/search/es-wp-query/README.md), I'm noticing that `posts_orderby` is one of the WP_Query filters that might have issues and I wondered if that might be related. But I'm not doing any filtering with this query, so I'm not sure how to tell.

Either way, I'm wondering if this is no longer a query that I can run through es-wp-query, or if there might be a fix? I've been unable to find any examples of other folks doing this, but surely it has happened?

## Steps to Reproduce the Problem

1. Disable Jetpack Search and a separately installed es-wp-query plugin
2. Enable Enterprise Search. See that it works successfully with searching the website as well as other WP_Query instances that do not have `orderby` as a parameter.
3. See that it does not work with queries that do have `orderby` as a parameter. That is, it does not return results ordered by the `menu_order`.

**Comment by rebeccahum** [comment]
> See that it does not work with queries that do have orderby as a parameter. That is, it does not return results ordered by the menu_order.

@jonathanstegall Hi! I'm unable to reproduce this. My steps are as follows:

1) On a blank install with ES, create a new page and set `menu_order` to 10 and create another one leaving default `menu_order`

2) Offload the below query

```
$args = [
	'es' => true,
	'orderby' => 'menu_order',
	'post_type' => 'page',
];
$query = new WP_Query( $args );
```

3) Go to Search Dev Tools, and see the below portion in the ES query:

```
  "sort": [
    {
      "menu_order": "desc"
    }
  ],
```

The above part tells me that it's working as expected. Especially since I can change `desc` to `asc` and see the results flipped. Do let me know if you have further details to help me reproduce this, thanks!

**Comment by jonathanstegall** [comment]
Sorry, @rebeccahum, I didn't realize you had commented! Thank you for looking into this. After reading your comment, I did a bunch of further looking. I'm still seeing the problem but I realize that it's a problem with my code, not with Enterprise search. Thanks again.
