### ISSUE TITLE
Missing mime type and PHP Warning with Automattic\VIP\Files\API_Client::upload_file()

### ISSUE THREAD

**Issue by dougaxe1** [Automattic/vip-go-mu-plugins#3174]
## Expected/Desired Behavior

Expect no PHP warning and successful mime type identification. I believe this is as simple as passing `$local_path` instead of just the filename

In public function upload_file( $local_path, $upload_path ), change:
```
		$file_name = basename( $local_path );
		$file_mime = self::detect_mime_type( $file_name );
```
to:
```
		$file_mime = self::detect_mime_type( $local_path );
```
(`$file_name` is not used anywhere else within this scope)

## Actual Behavior

In files/class-api-client.php: `Automattic\VIP\Files\API_Client::upload_file()` calls `Automattic\VIP\Files\API_Client::detect_mime_type()` with the `basename()` of `$local_path`. If `wp_check_filetype()` fails, or the function is called before `wp_get_current_user()`, the function falls back to `finfo_file()` which expects a full path, and throws a warning if not.

Example warning (sanitized stack trace):
```
Warning: finfo_file(phpXXXXXX): failed to open stream: No such file or directory in /chroot/var/www/wp-content/mu-plugins/files/class-api-client.php on line 187 [example.com] [/chrootwp-content/mu-plugins/files/class-api-client.php:187 finfo_file(), /chrootwp-content/mu-plugins/files/class-api-client.php:114 Automattic\VIP\Files\API_Client::detect_mime_type(), /chrootwp-content/mu-plugins/files/class-vip-filesystem-stream-wrapper.php:317 Automattic\VIP\Files\API_Client->upload_file(), Automattic\VIP\Files\VIP_Filesystem_Stream_Wrapper->stream_flush(), /chrootwp-includes/functions.php:2909 fclose(), /chrootwp-content/example.php:123 wp_upload_bits(), ...]
```

## Steps to Reproduce the Problem

1. Via cron or CLI, upload a file using `wp_upload_bits()`
1. Watch error logs or command output

**Comment by GaryJones** [comment]
Hi! Thanks for jumping in.

How would your proposed change account for the lack of basename() call now?
