### ISSUE TITLE
VIP Admin Notices do not persist dismissed notice

### ISSUE THREAD

**Issue by dougaxe1** [Automattic/vip-go-mu-plugins#3179]
## Expected/Desired Behavior

Upon dismissing a VIP Admin Notice (`Automattic\VIP\Admin_Notice\Admin_Notice`), the dismissal should be persisted to user meta.

## Actual Behavior

The dismissal is not persisted in user meta due to a timing bug in `admin-notice/js/script.js`. On window load `registerDismissHooks()` is called which attaches click events to each notice based on the selector `.vip-notice .notice-dismiss`. The `.notice-dismiss` button is added later during the WordPress core `makeNoticesDismissible()`.

## Steps to Reproduce the Problem

1. Create a VIP Admin Notice with matching conditions
2. Dismiss the notice via the UI (observe lack of network request)
3. Refresh the page
4. See same notice, again ☹️.

## (Optional) Additional notes

`makeNoticesDismissible()` is triggered by many events, including `$document.trigger( 'wp-updates-notice-added' );`. One option may be to use the same event to trigger running `registerDismissHooks()`. Another option would be to use a more general "live" selector capturing bubbling click events within the notice.

**Comment by sjinks** [comment]
Fixed in [d19bf3d](https://github.com/Automattic/vip-go-mu-plugins/commit/d19bf3d593604449dd759ce93e590e20b6c13177)
