### ISSUE TITLE
Incorrect hash for jetpack-idc

### ISSUE THREAD

**Issue by BronsonQuick** [Automattic/vip-go-mu-plugins#320]
If you clone the repository you'll see this error:
`Unable to checkout 'be82af4e72582511680b017101183578bd595c5c' in submodule path 'jetpack-idc'`

You can also see this happening in Travis:
https://travis-ci.org/Automattic/vip-go-mu-plugins/builds/167472996

**Comment by joshbetz** [comment]
This was working previously and just broke today. The commit exists https://github.com/Automattic/jetpack/commit/be82af4e72582511680b017101183578bd595c5c.

**Comment by BronsonQuick** [comment]
@joshbetz Yeah it's an odd one because I could browse to the hash but the submodule couldn't find the hash on the command line.

**Comment by simonwheatley** [comment]
Thanks for reporting this, @BronsonQuick. It looks like the Jetpack branch "diverged" 😃
