### ISSUE TITLE
VIP Admin Notices do not persist dismissed notice - selector bug

### ISSUE THREAD

**Issue by dougaxe1** [Automattic/vip-go-mu-plugins#3255]
_Originally posted by @sjinks in https://github.com/Automattic/vip-go-mu-plugins/pull/3192#discussion_r884009492_

Same unsolved issue from #3179.

This is still incorrect -- the HTML output is:
`<div data-vip-admin-notice="php8-migrations" class="notice notice-info vip-notice is-dismissible">`

The proper selector should be `[${dismissal_data.data_attribute}]` (has the attribute, not a value of the attribute).

**Comment by dougaxe1** [comment]
@sjinks (or other Automattician) - feel free to request review in the next PR if you're unable to test a fix locally.

**Comment by sjinks** [comment]
@dougaxe1 I think this has been fixed but not yet deployed: https://github.com/Automattic/vip-go-mu-plugins/pull/3246

**Comment by dougaxe1** [comment]
I think you're right -- and it may be deployed now: https://github.com/Automattic/vip-go-mu-plugins/releases/tag/v20220614.0. Thanks!

**Comment by sjinks** [comment]
The fix has been deployed, could you please take a look? Thank you!

**Comment by dougaxe1** [comment]
Yes - this works now! Thanks, again!
