### ISSUE TITLE
Hide DB upgrade notice from non Automatticians

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#331]
During upgrades, we run the db upgrade shortly after upgrading the code, but there can be a period of time when the 'DB upgrade is available' notice is shown to the site's users.

To prevent confusion and disruption, we should hide this notice from everyone - probably everyone that is not an Automattician.

This notice happens fairly early in the WP lifecycle, so hooking into it might be tricky.

**Comment by ethitter** [comment]
This'll be easy on multisite--we have the `do_mu_upgrade` filter at our disposal.

I'm not sure how we'll do this on single-site instances without filtering the `db_version` option. Core doesn't provide another escape: https://core.trac.wordpress.org/browser/tags/4.6.1/src/wp-admin/admin.php#L45.

**Comment by rinatkhaziev** [comment]
@nickdaugherty TBH I don't think hiding this is a good approach. I think WP doesn't allow you to log in unless the DB is updated, so this would be an endless login loop with no feedback to user.

**Comment by nickdaugherty** [comment]
Ah that would be a big problem. Okay let's shelve this idea.
