### ISSUE TITLE
Identify VIP Support users in New Device Notifications emails

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#343]
When a VIP Support user is added to a site and then logs in, this triggers a notification email from New Device Notifications (if active). We do not make it clear in the email that this user is with VIP Support, but we should.

/hattip @chris for the idea

**Comment by rebeccahum** [comment]
We do have some docs on VIP Support users: https://docs.wpvip.com/technical-references/restricting-site-access/site-access-for-vip-support/. But when we add a VIP Support user, their username is now prefixed with `vip_*` which should be enough IMHO.
