### ISSUE TITLE
Set severity level for VIP_Request_Block messages.

### ISSUE THREAD

**Issue by emrikol** [Automattic/vip-go-mu-plugins#3446]
## Expected/Desired Behavior

I think it would be nice if we switched the `VIP_Request_Block` class from using `error_log()` to `trigger_error( $message, E_USER_NOTICE )` so that request blocking messages could be easily filtered out of the error logs.

## Actual Behavior

We currently just ship out the message without a severity, making filtering harder to do when sorting through many messages.

**Comment by rinatkhaziev** [comment]
PRs welcome. I think it should be `E_USER_WARNING` though?
