### ISSUE TITLE
ElasticPress: the `format_hits_as_terms` returns a term as `stdClass` instead of `WP_Term`

### ISSUE THREAD

**Issue by jonathanstegall** [Automattic/vip-go-mu-plugins#3465]
## Expected/Desired Behavior

I reported this as a bug in ElasticPress here: https://github.com/10up/ElasticPress/issues/2912 with a fix here: https://github.com/10up/ElasticPress/pull/2913, but when I read through this repository it looks like VIP is running its own fork of ElasticPress? I understand there is ongoing work to bring in the 4.x changes, and if that means this fix will come in on its own, great! But I thought it might be helpful to add as a bug here, depending on how the fork maintenance works.

The [WP docs](https://developer.wordpress.org/reference/hooks/taxonomy_row_actions/) specify `WP_Term` as the object type for filters like `post_tag_row_actions`.

## Actual Behavior

Essentially, the `format_hits_as_terms` method in [these lines](https://github.com/Automattic/ElasticPress/blob/386db0162bf7801abb4d0831424d4b9bb145a0d1/includes/classes/Indexable/Term/QueryIntegration.php#L202-L247) is returning `$term` as an instance of `stdClass`, never converting it to `WP_Term` even though it does use the standard formatting for a `WP_Term` object. This causes problems with code that uses the `post_tag_row_actions` filter, which expects a `WP_Term` object.

## Steps to Reproduce the Problem

1. Index post_tag, at least, with some post tags.
2. Install The Events Calendar.
3. Go to `/wp-admin/edit-tags.php?taxonomy=post_tag&post_type=post` and search for a value that will return some tags.
4. The error I get is like this:

```php
Fatal error: Uncaught Error: Tribe\Events\Taxonomy\Taxonomy_Provider::event_tag_actions(): Argument #2 ($tag) must be of type WP_Term, stdClass given, called in /wp-includes/class-wp-hook.php on line 307
in /wp-content/plugins/the-events-calendar/src/Tribe/Taxonomy/Taxonomy_Provider.php on line 53

Call stack:

Tribe\E\T\Taxonomy_Provider::event_tag_actions()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/plugin.php:191
apply_filters()
wp-admin/includes/class-wp-terms-list-table.php:539
WP_Terms_List_Table::handle_row_actions()
wp-admin/includes/class-wp-list-table.php:1446
WP_List_Table::single_row_columns()
wp-admin/includes/class-wp-terms-list-table.php:345
WP_Terms_List_Table::single_row()
wp-admin/includes/class-wp-terms-list-table.php:253
WP_Terms_List_Table::display_rows_or_placeholder()
wp-admin/includes/class-wp-list-table.php:1289
WP_List_Table::display()
wp-admin/edit-tags.php:613
```

## (Optional) Additional notes

Again, if it's already going to be incorporated from ElasticPress, feel free to disregard, but I do see lots of mentions of this implementation being a fork so I hope it might be helpful!

**Comment by rebeccahum** [comment]
Thanks for flagging! Yes, we do indeed sync up with ElasticPress (we're just a bit behind right now). However, I've made a PR in our fork to get your changes in faster: https://github.com/Automattic/ElasticPress/pull/168
