### ISSUE TITLE
VIP_GO_ENV is not a boolean

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#354]
In a few spots, we're treating the `VIP_GO_ENV` constant as a boolean, but this is the environment name.

For clarity, it should be set to something like `local` in dev environments. Anywhere that is checking this constant should be updated to not treat it as a boolean.

**Comment by mjangda** [comment]
Spots where we use it:

> 001-cron.php
> 61:if ( VIP_GO_ENV && in_array( FILES_CLIENT_SITE_ID, $whitelisted_sites ) ) {

> misc.php
> 31:// Checking for VIP_GO_ENV allows this code to work outside VIP Go environments,
> 33:if ( defined( 'VIP_GO_ENV' ) && false !== VIP_GO_ENV ) {
