### ISSUE TITLE
wp_mail_from filter disable 

### ISSUE THREAD

**Issue by chetansatasiya** [Automattic/vip-go-mu-plugins#3638]
## Expected/Desired Behavior

1. We are able to remove this filter `add_filter( 'wp_mail_from', array( $this, 'filter_wp_mail_from' ), 1 );`

**Comment by sjinks** [comment]
Once #3646 gets deployed:

```php
remove_filter( 'wp_mail_from', [ VIP_SMTP::instance(), 'filter_wp_mail_from' ], 1 );
```

Meanwhile, you can try

```php
remove_all_filters( 'wp_mail_from' );
```

**Comment by chetansatasiya** [comment]
@sjinks When I expect to be deployed

**Comment by mjangda** [comment]
What is the reason for removing the filter, btw? Are you providing your own email plugin or SMTP service? Or something else?

**Comment by chetansatasiya** [comment]
@mjangda Yes, we are using our own SMTP and we have a setup different email(sender) setup based on the team. This filter is always keeping the sender as `donotreply@wpvip.com`

**Comment by chetansatasiya** [comment]
@mjangda @sjinks Any ETA when it shipped to the repo?

**Comment by sjinks** [comment]
Waiting for code review

**Comment by chetansatasiya** [comment]
@sjinks This one merged in the production version?

**Comment by rebeccahum** [comment]
@chetansatasiya This will be on Tuesday. It is currently in staging.
