### ISSUE TITLE
Require for WP_Feed_Cache fails fatally on 4.7

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#365]
See: https://github.com/Automattic/vip-go-mu-plugins/blob/568ba2fe26c2ad176a509782b459a6b379ff5792/vip-helpers/vip-syndication-cache.php#L4-L6

The files have been moved/split up, see: https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/feed.php#L672-L679

**Comment by fklein-lu** [comment]
Reported to Core in https://core.trac.wordpress.org/ticket/39027 because the file should have been deprecated instead of removed.

**Comment by fklein-lu** [comment]
This was fixed in Core in https://core.trac.wordpress.org/changeset/39459
