### ISSUE TITLE
is_amp_endpoint() called before WP is ready

### ISSUE THREAD

**Issue by kasparsd** [Automattic/vip-go-mu-plugins#3754]
## Expected/Desired Behavior

1. No PHP warnings are produced.

## Actual Behavior

The following PHP warning is triggered when loading any page or post on the frontend.

```
Notice: Function amp_is_available was called incorrectly. `amp_is_available()` (or `amp_is_request()`, formerly `is_amp_endpoint()`) was called too early and so it will not work properly. WordPress is currently doing the `init` hook. Calling this function before the `wp` action means it will not have access to `WP_Query` and the queried object to determine if it is an AMP response, thus neither the `amp_skip_post()` filter nor the AMP enabled toggle will be considered. It appears the must-use plugin with slug `jetpack-11.3` is responsible; please contact the author. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 2.0.0.)
```

which is triggered by `mu-plugins/jetpack-11.3/modules/carousel/jetpack-carousel.php:120`:
 https://github.com/Automattic/jetpack/blob/ff0c0fbcdb3cb6b72822aaac49e6b093746326ed/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php#L120

## Steps to Reproduce the Problem

1. Use Jetpack bundled with mu-plugins on WordPress VIP.
2. Enable the Carousel module.
3. Visit any post or page.
4. Notice the PHP warning displayed or logged.

## (Optional) Additional notes

I'm filing it here instead of the Jetpack repo because very few users have Jetpack added as a mu-plugin and there is probably a quicker way to fix this on VIP.

**Comment by rinatkhaziev** [comment]
Hey @kasparsd , 

I switched a test site running twentytwentyone on VIP to 11.3.2 (which is what we have deployed currently), enabled carousel, created a new post with a carousel (just to be extra sure :)) but wasn't able to reproduce.

Are you able to reproduce this consistently both on a real VIP site and VIP Local Dev Env?

> Jetpack added as a mu-plugin and there is probably a quicker way to fix this on VIP.

Except for very-very rare circumstances we deploy exactly what Jetpack has tagged in [Jetpack production repo](https://github.com/Automattic/jetpack-production).

**Comment by kasparsd** [comment]
Sorry for the confusion — the site also needs to have the AMP plugin https://wordpress.org/plugins/amp/ enabled for the “Jetpack_AMP_Support” class to exist and the check to run. I totally missed this from the steps to replicate the issue.
