### ISSUE TITLE
VaultPress can trigger a fatal error on PHP 8.0

### ISSUE THREAD

**Issue by joemcgill** [Automattic/vip-go-mu-plugins#3821]
## Expected/Desired Behavior

When VaultPress attempts to retrieve messages from VP servers, in `VaultPress::get_messages()` it should not trigger any fatal errors if the message is not a string.

## Actual Behavior

In certain cases, when VaultPress attempts to retrieve messages from VP servers, the following error might be triggered.

> Fatal error: Uncaught Error: base64_decode(): Argument #1 ($string) must be of type string, array given
in /var/www/wp-content/mu-plugins/vaultpress/vaultpress.php on line 469

## Steps to Reproduce the Problem

I'm unable to reliably reproduce this issue, since it only occurs when the VP servers return an error, but can see that in [this code](https://github.com/Automattic/vaultpress/blob/2.2.1/vaultpress.php#L2310-L2315). The function that gets messages from the server expects an array whenever there is an error, which will always cause a fatal when passed directly to `base64_decode()` without first checking to see if it is a string.

## (Optional) Additional notes

Any other relevant information to help with debugging/implementation.

**Comment by sjinks** [comment]
Hi, could you please report this issue to [Automattic/vaultpress](https://github.com/Automattic/vaultpress)?

Thank you!
