### ISSUE TITLE
PHP 8+ Undefined Array Key in Codebase Manager

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/vip-go-mu-plugins#4116]
## Details

In some cases, sites running PHP 8 or above will see the following PHP Warning:

```
PHP message: PHP Warning: Undefined array key 2 in /var/www/wp-content/mu-plugins/codebase-manager/plugins/plugins-manager.php on line 49 
```

https://github.com/Automattic/vip-go-mu-plugins/blob/develop/codebase-manager/plugins/plugins-manager.php#L41-L59

## Expected Behavior

No PHP WARNINGs or ERRORs ;) 

## Actual Behavior

PHP WARNINGS ;)

**Comment by WPprodigy** [comment]
There must be a plugin / custom code that is adding to the global `$menu` variable incorrectly.

Core WordPress is going to be throwing errors as well, such as from here: https://github.com/WordPress/WordPress/blob/9fd50db9784d9a1c1f035fd88237f6cbcb5d751a/wp-admin/menu-header.php#L86

There must be something that is not using https://developer.wordpress.org/reference/functions/add_menu_page/ correctly, or doing some strange direct manipulation. We could add extra safeguards to our code, but there's still going to be loads more of PHP errors from WP core.
