### ISSUE TITLE
Client MU Plugins not loaded on wp-activate.php

### ISSUE THREAD

**Issue by dougaxe1** [Automattic/vip-go-mu-plugins#4315]
## Expected/Desired Behavior

Expected behavior for bugs:

- Client MU Plugins are loaded on wp-activate.php
- Client MU Plugins are loaded even if `--skip-plugins` is added to a WP-CLI command

A Client MU Plugins which affects some aspect of the signup process cannot act on the signup if it's not loaded during activation. Relatedly, theme code (which is loaded) may have dependencies on Client MU Plugins which is to be expected since MU Plugins should ALWAYS load.

The documentation for WP-CLI states that even if `--skip-plugins` is set, mu-plugins are still loaded. client-mu-plugins are an extension of this on the VIP platform and should be treated the same.
> [Skip loading all or some plugins. Note: mu-plugins are still loaded.](https://make.wordpress.org/cli/handbook/references/config/)

## Actual Behavior

[vip-utils.php](https://github.com/Automattic/vip-go-mu-plugins/blob/develop/vip-helpers/vip-utils.php#L1286) has a function controlling the loading of plugins, but in [z-client-mu-plugins.php](https://github.com/Automattic/vip-go-mu-plugins/blob/develop/z-client-mu-plugins.php#L120) it is erroneously used to determine whether Client MU Plugins are loaded or not. This conditional gate should not be used for Client MU Plugins, only for regular plugins.

## Steps to Reproduce the Problem

1. Add a file to client-mu-plugins with `<?php die( 'test' ); ?>`
1. Run wp-activate.php -- note that it does not die
1. Run a WP CLI command with the `--skip-plugins` flag -- note that it does not die

## (Optional) Additional notes

The unexpected behavior of not loading Client MU Plugins may constitute a security issue on some sites, or cause unexpected fatal errors. Ironically, the latter issue is what apparently what [prompted the conditional in the first place](https://github.com/Automattic/vip-go-mu-plugins/commit/c7d5f4a56767ae666d5065feab6724b08ea97ca0). Also the fact that this condition has been around for 5 years makes this a breaking change which requires plenty of testing.

**Comment by rinatkhaziev** [comment]
Hi @dougaxe1 ,

Thanks for the report. The `wp-activate.php` issue is actually a regression introduced in #4247 
We're going to revert in #4329 and then a follow-up in #4328

The original fix was to solve for fatals where during actual installation client-mu-plugins would load and break in random ways (e.g.  table wouldn't exist yet and it would result in fatals.

**Comment by johnbillion** [comment]
Related: https://core.trac.wordpress.org/ticket/23197

**Comment by rinatkhaziev** [comment]
![image](https://user-images.githubusercontent.com/459254/235201553-3a5eec54-903d-4192-b791-614e9e616293.png)
@johnbillion I guess something came up :)
