### ISSUE TITLE
Non-prod bar with 100% width obstructs content editing clicks.

### ISSUE THREAD

**Issue by emrikol** [Automattic/vip-go-mu-plugins#4375]
## Expected/Desired Behavior

I expect the `#vip-non-prod-bar` to not get in the way of content editing.

## Actual Behavior

Due to [its width being 100%](https://github.com/Automattic/vip-go-mu-plugins/blob/8d5ca4530459e634c8b2fa0776fa62e525a3be3f/vip-helpers/vip-non-production.php#L43), even though the div is blank, clicking anywhere in the horizontal plane of the div will result in the click not going to the application below, but will be eaten by `#vip-non-prod-bar`

## Steps to Reproduce the Problem

1. Set up a non-prod site with the bar active.
1. Try to click on something in the horizontal plane of the bar.
1. Watch the click not register

## (Optional) Additional notes

For example:

<img width="2303" alt="image" src="https://user-images.githubusercontent.com/3060583/233159007-0b04e152-d54a-41c4-ba3d-55abf7b6a480.png">

If we instead remove the `100%` width:

<img width="183" alt="image" src="https://user-images.githubusercontent.com/3060583/233159127-5a9143e9-3033-4bc1-8fed-4238aa110a59.png">

<img width="275" alt="image" src="https://user-images.githubusercontent.com/3060583/233159213-46583e54-e93e-4985-8492-8b4324caaaec.png">

Then clicks can flow through to the underlying application.

Happy to make a PR for this, possibly one-line diff ;)

**Comment by rinatkhaziev** [comment]
@emrikol a PR is always nice :)

**Comment by nexstar-tom-j-nowell** [comment]
Noting that this is also an issue even when it has the desired dimensions, it's super frustrating at the moment working on a settings page that constantly sits underneath the non prod bar and I have to edit it out or faff around with filters to remove the bar entirely
