### ISSUE TITLE
Alloptions: Ability to switch autoload value for an option

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#453]
It would be nice to have command that lets us easily swap the `autoload` value for any given option on a site.

It should:

- [ ] Update the value in the database
- [ ] Flush the necessary caches

Might be good to upstream to wp-cli and/or core.

**Comment by nickdaugherty** [comment]
@trepmal noticed the other day that WP-CLI includes a `--autoload` parameter to `option update` out of the box, so I think we can just use that.

https://developer.wordpress.org/cli/commands/option/update/#options

**Comment by trepmal** [comment]
After some experimenting, this may not work as smoothly as we'd like. A separate direct command may be desirable.

Like `update_option()`, `autoload` is only updated if the value is changed.

---
given this db row:

option_name | option_value | autoload
------------- | ------------ | ---------
greeting | hi | yes

❌ `update_option( 'greeting', 'hi', 'no' );` // value = old value, bails early
❌ `wp option update greeting hi --autoload=no` // value = old value, bails early
❌ `wp option update greeting --autoload=no` *it appears to think, but it actually is a prompt for you to type a new value and hit ctrl+D. if same as old value, guess what, bails early

It seems that the only way to make this work is 1) change the value or 2) use SQL.

**Comment by nickdaugherty** [comment]
Ah, yes that would greatly limit the utility for us then, thanks for looking into it. Ok, let's go ahead with a separate command.

**Comment by trepmal** [comment]
https://github.com/trepmal/option-autoload-cli

**Comment by GaryJones** [comment]
Fixed in #1496.
