### ISSUE TITLE
Removing category base using wpcom_vip_load_category_base() forces other functions to return a relative URL

### ISSUE THREAD

**Issue by anigeluk** [Automattic/vip-go-mu-plugins#4541]
If you use the [wpcom_vip_load_category_base() function](https://github.com/Automattic/vip-go-mu-plugins/blame/c18071981baad1c3163a3f0d04a3f85c6d35323b/vip-helpers/vip-permastructs.php#L39) to remove the category base then it forces a relative URL to be returned via the [category_link](https://github.com/Automattic/vip-go-mu-plugins/blob/c18071981baad1c3163a3f0d04a3f85c6d35323b/vip-helpers/vip-permastructs.php#L48) filter

This impacts calls to[ get_term_link()](https://developer.wordpress.org/reference/functions/get_term_link/) and [get_category_link()](https://developer.wordpress.org/reference/functions/get_category_link/), making them return relative URLs instead of absolute URLs.

This then has further knock-on impacts on code that relies on the normal absolute URL behaviour of those functions, including, for example, our own [vip-cache-Manager](https://github.com/Automattic/vip-go-mu-plugins/blob/c18071981baad1c3163a3f0d04a3f85c6d35323b/vip-cache-manager/vip-cache-manager.php#L703) when it tries to get a URL to purge the cache.

## Expected/Desired Behavior

Ideally, this should be changed so that calls to get_term_url and get_category_link will both return absolute URLs even if you have used wpcom_vip_load_category_base. This is the normal behaviour when `wpcom_vip_load_category_base()` has not been used.

However, there is a risk that this may have other impacts as the issue has been present for at least 8 years.

```
wp> get_category_link(1);
=> string(46) "http://localtest.local/uncategorized/"
```

## Actual Behavior

If you have removed the category base you will get relative URLs returned.

```
wp> get_category_link(1);
=> string(15) "/uncategorized/"
```

## Steps to Reproduce the Problem

1. Using WP-CLI or theme code, call `get_category_link(CATEGORYID)` with a valid category ID and note the absolute URL.
2. Add `wpcom_vip_load_category_base('');` to the themes function file or an mu-plugin.
3. Repeat step 1 and note that you now get a relative URL returned instead of an absolute one.

**Comment by sjinks** [comment]
This function doesn't work as expected at all.

```
wp> get_category_link(1)
string(59) "http://vip-testing-wwa83.go-vip.net/category/uncategorized/"
wp> wpcom_vip_load_category_base('xxx');
NULL
wp> get_category_link(1)
string(59) "http://vip-testing-wwa83.go-vip.net/category/uncategorized/"
```

**Comment by philipjohn** [comment]
Any chance this can be re-opened? We're (XWP working on a VIP client) dealing with this issue now and it's causing some sitemaps (via Yoast SEO) to return relative URLs which is naturally breaking search engine indexing.
