### ISSUE TITLE
Disable do_pings by default

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#462]
Something like:

```
add_filter( 'schedule_event', function( $event ) {
    if ( 'do_pings' === $event->hook ) {
        return false;
    }
    return $event;
} );
```

With the option to enable, if preferred.

**Comment by ethitter** [comment]
I like the concept. If we move away from an anonymous function, users could easily restore Core's behaviour without needing an option.

Related to this, I need to open a Core ticket about how `do_pings` jobs are scheduled, as the current approach leads to unnecessary duplication.

**Comment by ethitter** [comment]
Related, there shouldn't be so many of these events to begin with (IMO): https://core.trac.wordpress.org/ticket/39828.
