### ISSUE TITLE
Increase or Allow DEFAULT_SEARCH_LENGTH to be Filterable to Support Encoded Searches

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/vip-go-mu-plugins#4833]
## Desired Behavior

In #1625 we set `DEFAULT_SEARCH_LENGTH` to 255. This was originally set to prevent a bug with search string length which has been reported to be fixed. 

In some cases, 255 is not long enough. For example, in non-English languages, character encoding may be used in search which increases the length. For example, in Arabic character encoding may mean that there are 4 characters for each ASCII character.

The request here is to increase the `DEFAULT_SEARCH_LENGTH` length, or make it filterable with the `parse_query` filter which is currently not possible due to that filter using `PHP_INT_MAX`:
https://github.com/Automattic/vip-go-mu-plugins/blob/develop/search/includes/classes/class-search.php#L597C79-L597C90

If there is a reason why the max needs to be set at 255, then let's make sure to document that in this issue.

## Actual Behavior

It is possible to increase the default length up to the max with the `vip_search_char_length` filter (#3531) but characters will be truncated to the max set (currently 255)

## Steps to Reproduce the Problem

1. Search for an encoded string such as `https://example.com/search/%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9%20%D8%AA%D8%B5%D8%AF%D8%B1%20%D8%B5%D9%83%D9%88%D9%83%D8%A7%D9%8B%20%D8%A8%D9%82%D9%8A%D9%85%D8%A9%209.6%20%D9%85%D9%84%D9%8A%D8%A7%D8%B1%20%D8%AF%D9%88%D9%84%D8%A7%D8%B1%20%D8%A8%D8%A2%D8%AC%D8%A7%D9%84%20%D8%A7%D8%B3%D8%AA%D8%AD%D9%82%D8%A7%D9%82%20%D8%AD%D8%AA%D9%89%202038 `
1. Note that there are no results and the max length

**Comment by mnagdycnn** [comment]
@rebeccahum There is an issue with this for non-latin languages. Usually each character gets encoded into 4 bits. Giving the fact this PR trims the search query up to only 255 characters. It is possible that if someone is searching with a short search query in one of these languages to be corrupted by this slicing of strings. Therefore, I am suggesting to extend the search to 1020 or 3000 characters at most. The logic behind choosing 1020 as a max is that it's the 4 bits multiplied by the 255.

**Comment by rebeccahum** [comment]
The maximum was set at 255 because we were seeing bots send in long strings which creates slow ES queries due to tokenization. 

@mnagdycnn I'm not against extending it, but let's start with doubling it to 510 since we want to evaluate impact before extending it any further.

**Comment by BrookeDot** [comment]
Sounds good @rebeccahum! I'm wondering if another solution could be to detect, or allow the customer to set the language at the application layer and then only extend the search lengths when it has been manually defined. That may be outside the scope of this issue but wanted to throw that out there as another idea for solving this.

**Comment by rebeccahum** [comment]
@BrookeDot Unfortunately, dynamically setting the search lengths isn't as straight forward since using `get_locale()` isn't always set correctly and they may be using third-party multi-language plugins.

**Comment by BrookeDot** [comment]
That makes sense @rebeccahum! So it would be the addition of a constant or filter, but as you mentioned the concern here is making sure that we are able to block bots from causing problems with tokenization. 

Closing this for now makes sense and we can open a new issue if needed.
