### ISSUE TITLE
Offload Bulk Actions to cron

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-go-mu-plugins#484]
Core's `WP_List_Table` class provides the ability to edit or delete many posts, which can introduce performance problems. #475 placed limits on how many posts can be edited in one request. To improve further upon that effort, tasks should be offloaded to cron, and a higher limit imposed.

To keep things interesting, bulk actions are processed in `wp-admin/edit.php`, acting on `$_REQUEST` arguments, with no designated way to intervene. Fortunately, the `load-edit.php` action fires before the request is parsed, so we can use it to capture the data needed to schedule an event, then remove that data from `$_REQUEST` to bypass Core's default handling. Displaying a message requires filtering the return url via `handle_bulk_actions-{$screen_id}` to include a `$_GET` argument we can then detect in an `admin_notices` handler.

Core doesn't support custom bulk actions, so we don't need to worry about handling for that.

Core's supported actions are:
* `delete_all`
* `trash`
* `untrash`
* `delete`
* `edit`

Most of these are straightforward, but `delete_all` is a bit of a special case. Unfortunately, since most of the input parsing for this isn't wrapped in functions we can reuse, this will duplicate a considerable amount of code from Core.

**Comment by mjangda** [comment]
We also need to think about what the user experience for this will be like. We definitely want to implement locking for any posts that have queued async bulk actions (or some other way to avoid potential issues).

**Comment by mjangda** [comment]
> Unfortunately, since most of the input parsing for this isn't wrapped in functions we can reuse, this will duplicate a considerable amount of code from Core.

I wonder if there's some way we could just have the cron event trigger the request on behalf of the user asynchronously?

Another idea could be to skip the cron idea and use AJAX to process posts one at a time? That could be something upstream-ed to core as well. Maybe use REST API?

**Comment by ethitter** [comment]
For locking, this is already somewhat taken care of for us. `bulk_edit_posts()` checks the lock before updating a post. If it can't update, it returns the post ID, so we could re-queue the changes, or save the failed IDs in an option and display a notice for the user.

As for running the tasks without duplicating more than necessary, a cron job that calls the REST API is a nice middle ground. Core already process posts one at a time, but it doesn't pause or do any memory cleanup, nor understandably, does it use much caching. Offloading to a cron job can address much of this. For bulk edits, we could slice the array to process it in smaller batches, for example.

**Comment by ethitter** [comment]
Work started in https://github.com/Automattic/bulk-edit-cron-offload.

**Comment by mjangda** [comment]
Going to close this out; not really a huge need right now.
