### ISSUE TITLE
`file_get_contents()` repeatedly called on not existing file

### ISSUE THREAD

**Issue by antonioeatgoat** [Automattic/vip-go-mu-plugins#4878]
## Expected/Desired Behavior

`file_get_contents` at [this](https://github.com/Automattic/vip-go-mu-plugins/blob/9cea8f3ed04e0130f1470013745ef600fb8d08b4/integrations/integration-vip-config.php#L92) line should stop to produce Warnings if the file checked doesn't exist (whatever PHP version is being used).

## Actual Behavior

Right now, that line produces a warning in PHP 8+ if the file doesn't exists. This is probably caused by the fact the the Error Control Operator (`@`) changed its behavior from PHP 8.

Specifically the errors are triggered for both Parsely and Block Data Api integrations:

`file_get_contents(/var/www/config/integrations-config/parsely-config.php): Failed to open stream: No such file or directory`
`file_get_contents(/var/www/config/integrations-config/block-data-api-config.php): Failed to open stream: No such file or directory`

## Steps to Reproduce the Problem

Just loading any page in an environment where Warnings are visible should be enough (Probably also having the integrations disabled is required?).

## Additional notes

Is invalidating the cache of the config file before checking for its existence a doable solution for you? This way `file_get_content` can be just avoided.

Otherwise is there any chance to not reach that part of code at all if the integrations are not active? So the part would be just skipped for whose are not supposed to use it.

**Comment by gmazzap** [comment]
We are collecting logs for our sites, and we have _several thousands_ appearances of such warnings in our logs, literally flooding them.

Why not just clearing the stat cache without the `if` as @antonioeatgoat proposed?

Considering `file_get_contents` call is expensive enough and that you could use a static variable to avoid multiple calls per request, I guess this will not be more expensive if not _less_ expensive.

Something along the lines of:

```php
protected function get_vip_config_from_file( string $slug ) {

    static $config = [];
    if  ( isset( $config[ $slug ] ) ) {
        return $config[ $slug ];
    }

    $config_file_dir      = ABSPATH . 'config/integrations-config/';
    $config_file_data_dir = $config_file_dir . '..data/';
    $config_file_name     = $slug . '-config.php';
    $config_file_path     = $config_file_dir . $config_file_name;

    clearstatcache( true, $config_file_path );
    clearstatcache( true, $config_file_data_dir );
    clearstatcache( true, $config_file_data_dir . $config_file_name );

    $config[ $slug ] = is_readable( $config_file_path )
        ? require $config_file_path
        : null;

    return $config[$slug];
}
```

**Comment by mehmoodak** [comment]
Thanks for the report. Looking into it.

> Why not just clearing the stat cache without the if as @antonioeatgoat proposed?

This solution is under consideration.

> you could use a static variable to avoid multiple calls per request

Not doing multiple calls per request, we only read config file of each integration once.

**Comment by mehmoodak** [comment]
The issue itself has been fixed but the code is yet to release on production.

**Comment by antonioeatgoat** [comment]
@mehmoodak thank you! Is there any ETA for it?

**Comment by mehmoodak** [comment]
ETA is Monday on `staging` and Tuesday on `production`.
