### ISSUE TITLE
Comment counts not being updated

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#493]
To reproduce:

0. Check `/wp-admin/edit-comments.php`, and note the numbers, e.g. `All (0) | Pending (0) | Approved (0) | Spam (1) | Trash (3)`
1. Change comments by trashing some, adding some, etc
2. Check `/wp-admin/edit-comments.php`, and compare the numbers (I see no change, and numbers do not reflect the status of comments)
3. Flush cache `wp cache flush`
4. Refresh `/wp-admin/edit-comments.php`, and compare the numbers (I now see counts which reflect the status of comments)

Expected: Comment counts should reflect the status of comments.

**Comment by simonwheatley** [comment]
Maybe related to https://github.com/Automattic/vip-go-mu-plugins/pull/477 ?

Ping @emrikol 🙂

**Comment by simonwheatley** [comment]
Comment count is [cached for 30 minutes](https://github.com/Automattic/vip-go-mu-plugins/blob/72c30ad792e3920381a9b1754cb236cacf8eb7d1/vip-helpers/vip-caching.php#L633); see [announcement lobby post](https://lobby.vip.wordpress.com/2016/03/23/wordpress-performance-improvements/).

I guess this is particularly noticeable on test sites with smaller content quantities. Maybe it's worth considering showing some notice to admins (perhaps only when they do something to change the number of comments in a category)… or perhaps that's just noise on a real site, with significant volumes of content.

**Comment by rebeccahum** [comment]
This is no longer applicable since it looks like we no longer seem to be doing this (e.g. we are no longer hooking onto `wp_count_comments`).
