### ISSUE TITLE
Unable to activate shared plugins whose main file does not match folder name

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#50]
`WPCOM_VIP_Plugins_UI::validate_plugin()` doesn't pass for plugins that don't fit the `$plugin/$plugin.php` pattern, such as WP-API.

This function needs rewritten to allow those, as they are valid plugins, according to `get_plugins()`, which is what is used to build the list.

**Comment by mjangda** [comment]
This was fixed.
