### ISSUE TITLE
Add Jetpack Site ID to debug bar

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#500]
Probably up in the main horizontal bar.

**Comment by rebeccahum** [comment]
@nickdaugherty I could see this being particular useful to have quick access during debugging. However...

1) Should this be accessible to users without the role of `vip_support`, such as ones with the `manage_options` caps? 
2) If 1) is 'yes', what use cases would those users need the site ID for?

**Comment by rebeccahum** [comment]
Closing because Debug bar is going away.
