### ISSUE TITLE
Bump Advanced Post Cache to master

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#505]
@mboynes noted that our Advanced Post Cache submodule is stuck on [this branch](https://github.com/Automattic/advanced-post-cache/commits/fix/4-temporary-fix-only). We should merge that in to `master` (assuming it makes sense to) and bump the copy here as well.

**Comment by markosamuli** [comment]
The module seems to have issue https://github.com/Automattic/advanced-post-cache/issues/8 affecting our local development environment when we pulled down these plugins.

**Comment by mjangda** [comment]
We can get rid of the branch completely as the filter is not in use by any sites.

**Comment by mjangda** [comment]
Sorry about the wait, @markosamuli; we've deployed the latest version of Advanced Post Cache so should hopefully resolve your issue.
