### ISSUE TITLE
Public repo out of date

### ISSUE THREAD

**Issue by keg** [Automattic/vip-go-mu-plugins#517]
Hi, saw issue #194 and it looks like the [public repo](https://github.com/Automattic/vip-mu-plugins-public) should still be around? FWIW It is a ~month behind on commits.  Only happen to notice because we had an old env pointed at public.

**Comment by mjangda** [comment]
Thanks for flagging this Kevin. Looks like the script that pushes to the public repo from Travis is breaking. Will look into it.

**Comment by jasonbahl** [comment]
any update on this? would be good to be able to have a repo with all the files in one place for debugging, etc.

**Comment by mjangda** [comment]
Sorry about the wait here; this has been fixed as of #610.
