### ISSUE TITLE
Delete core meta_key INDEX after dbDelta

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#521]
We added a new `meta_key_value` INDEX in #445. Unfortunately, `dbDelta` only adds INDEXes, but doe not delete them. We should probably have a process that deletes the core INDEX after `dbDelta` since it's no longer necessary.

**Comment by rebeccahum** [comment]
@sjinks This might be of interest to you since you're working on CANTINA-852.

**Comment by sjinks** [comment]
Related: #2893

**Comment by sjinks** [comment]
It probably makes sense to create a one-time cron job that will run these queries:

```sql
ALTER TABLE wp_postmeta LOCK=NONE, ALGORITHM=NOCOPY, ADD KEY vip_meta_key_value (meta_key(191), meta_value(100));
ALTER TABLE wp_postmeta LOCK=NONE, ALGORITHM=NOCOPY, DROP KEY meta_key, ADD KEY meta_key (meta_key(191), meta_value(100));
ALTER TABLE wp_postmeta LOCK=NONE, ALGORITHM=NOCOPY, DROP KEY vip_meta_key_value;
```

They will normalize the index without locking the tables.

If there are other keys to drop, we can always use

```sql
ALTER TABLE table_name LOCK=NONE, ALGORITHM=NOCOPY, DROP KEY index_name;
```
