### ISSUE TITLE
vip post-import CLI command

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#526]
A `vip post-import` command that is relatively lightweight (so we can run it in the API) would be nice. To start, I'm thinking it would:

1. Delete `jetpack_options`
1. search-replace <old_url> <new_url> in wp*_options, wp_site, wp_blogs
1. wp cache flush

**Comment by mjangda** [comment]
We may need a `pre-import` command as well that disconnects Jetpack (if connected) and maybe other things.
