### ISSUE TITLE
Bulk Editing is Disabled With Less than 20 Pages

### ISSUE THREAD

**Issue by chrisscott** [Automattic/vip-go-mu-plugins#527]
<img width="1205" alt="screen shot 2017-03-22 at 18 57 59" src="https://cloud.githubusercontent.com/assets/41005/24224673/c4c34404-0f32-11e7-971c-533e5307bf35.png">

**Comment by ethitter** [comment]
This is a quirk of Core, where the `posts_per_page` argument isn't accessible for pages.

The whole thing will go away once https://github.com/Automattic/bulk-actions-cron-offload/pull/1 is merged and that plugin is added here.

**Comment by rebeccahum** [comment]
This doesn't seem to be occurring anymore on attempt to reproduce. Closing.
