### ISSUE TITLE
flush Varnish cache on home/site url change

### ISSUE THREAD

**Issue by david-binda** [Automattic/vip-go-mu-plugins#528]
We should automagically flush the page level cache in case the URL of a site is changed in order to prevent redirect loops.

**Comment by mjangda** [comment]
Out of curiosity, in what contexts does the redirect loop happen? Or is it anytime the home/siteurl is changed?

**Comment by david-binda** [comment]
I haven't dug really deep into the issue since there was some time pressure for getting that resolved asap. 

Here's what happened today:

1) a site URL was changed via wp-admin
2) DNS were switched
3) trying to reach the new URL lead to a redirect loop which involved the original URL and the new one
4) flushing Varnish cache fixed the issue

**Comment by rinatkhaziev** [comment]
Closing, both us and customers have the ability to flush cache if need be either via VIP-CLI or running a WP-CLI command.
