### ISSUE TITLE
SMS two factor provider configuration confirmation

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#535]
Unlike the TOTP method, there’s no confirmation that the phone number you’ve entered is correct. 

It might be nice to send the user a “check code” which they enter, the provider confirms the code worked, and then we know it’s all configured correctly before they next have to log in (which would be a bad time to discover a misconfiguration).

**Comment by dchymko** [comment]
This needs to be redeployed.

**Comment by dchymko** [comment]
Redeployed
