### ISSUE TITLE
SMS two factor code sender

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#536]
The SMS codes come through from a random US number. It would be nice if they were from either "WordPress.com VIP" or perhaps even the site name.

Can we use a readable “from” for the SMS? Twilio docs state:

> The ‘from’ attribute takes a valid phone number or alphanumeric sender ID as an argument. If a phone number is used, it must be a number that you’ve purchased from or ported to Twilio.
> 
> Alphanumeric sender IDs can only be used when sending messages to countries where the feature is supported. Alphanumeric sender IDs are limited to 11 characters. Accepted characters include both upper- and lower-case ASCII letters, the digits 0 through 9, and space: [A-Za-z0-9 ]. The sender ID must represent or be associated with your company brand.
> – https://www.twilio.com/docs/api/twiml/sms/message

**Comment by joshbetz** [comment]
> The SMS codes come through from a random US number.

The number isn't really random -- it's [the number we registered](https://github.com/Automattic/vip-go-mu-plugins/blob/master/lib/sms.php#L6) with Twilio. This is also how SMS works on WordPress.com. Unfortunately US and Canadian carriers [don't support](https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID) alphanumeric sender IDs, so I don't think that's an option.

The REST API docs state:

> A Twilio phone number (in E.164 format) or alphanumeric sender ID enabled for the type of message you wish to send. Phone numbers or short codes purchased from Twilio work here. You cannot (for example) spoof messages from your own cell phone number.

https://www.twilio.com/docs/api/rest/sending-messages

**Comment by simonwheatley** [comment]
> The number isn't really random -- it's the number we registered with Twilio. This is also how SMS works on WordPress.com. 

Yeah, "random" was a bad choice of words, I really meant that it's non-obvious to the recipient 😬

> Unfortunately US and Canadian carriers don't support alphanumeric sender IDs, so I don't think that's an option.

Still worth doing for the countries with modern mobile networks, perhaps? 😎

**Comment by ethitter** [comment]
> Yeah, "random" was a bad choice of words, I really meant that it's non-obvious to the recipient 😬

For what it's worth, at least in the US, SMS-based 2fa universally comes from some random number; it's usually a short code ([not the WP kind](https://en.wikipedia.org/wiki/Short_code)), which makes repeat-senders a bit easier to spot, but it lacks any other identifier outside of the message content. This is all to say that US recipients probably won't notice or care about the number.

> Still worth doing for the countries with modern mobile networks, perhaps? 😎

Probably, though it's not as simple as just switching something in the Twilio account, as we learned from WP.com, because certain countries require pre-registration of various sorts ([#](https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID)).

**Comment by simonwheatley** [comment]
Just looking through my SMS messages for examples:

* Telegram appears as "Telegram"
* Apple appears as a mobile/cell number
* Slack appears as a mobile/cell number

Seems some significant players have the same UX issue.

> Probably, though it's not as simple as just switching something in the Twilio account, as we learned from WP.com, because certain countries require pre-registration of various sorts

This is the kicker 😞

Closing, as we seem enhancement seems in disfavour.
