### ISSUE TITLE
Jetpack Force 2FA: Enforce for all users

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#540]
We currently only enforce jetpack-force-2fa for users that have manage_options caps, but we enforce two-factor for all users. For consistency and simplicity, we should enforce two-factor for all users.

**Comment by joshbetz** [comment]
https://github.com/Automattic/jetpack-force-2fa/pull/21

**Comment by joshbetz** [comment]
We'd probably want to put this behind the `wpcom_vip_force_two_factor` filter for now because jetpack-force-2fa is already enabled if you have SSO enabled.

**Comment by nickdaugherty** [comment]
@joshbetz I believe this has been addressed by recent work on 2FA?
