### ISSUE TITLE
Query Monitor doesn't load locally

### ISSUE THREAD

**Issue by chrisscott** [Automattic/vip-go-mu-plugins#541]
Likely because we [check for a cap](https://github.com/Automattic/vip-go-mu-plugins/blob/master/query-monitor.php#L38) that is added in an [activation hook](https://github.com/johnbillion/query-monitor/blob/9b604e8972b09dad9ba17df84af5770118068fb6/classes/Activation.php#L26).

**Comment by ethitter** [comment]
As a temporary solution, you can add `add_filter( 'debug_bar_enable', '__return_true', 999 );` to your `vip-config.php`, or an mu-plugin that loads early; I have it in one called `000-a-sandbox-helper.php`.

**Comment by ethitter** [comment]
Err, `wpcom_vip_qm_enable`, not `debug_bar_enable`. 😃

**Comment by johnbillion** [comment]
This can be closed now, QM no longer uses the activation hook to assign its cap.
