### ISSUE TITLE
Load Debug Bar earlier

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#544]
Currently we hook Debug Bar into `init`, which is fairly late and misses some stuff. This was primarily done so we could limit it by user - but maybe we should look at proxy / sandbox status instead.

**Comment by joshbetz** [comment]
Is there anything specifically that you're worried about missing? We could hook on `set_current_user`, which is a bit earlier.

**Comment by nickdaugherty** [comment]
Ya specifically the remote request logging hooks in in the class's `init()`, which in our case happens at `init`, so we miss some early stuff.

https://github.com/Automattic/vip-go-mu-plugins/blob/40ed77652cd0cfbda59bfc59978bd57fa69ac755/vip-helpers/vip-debug-bar-panels.php#L285

**Comment by nickdaugherty** [comment]
We could rework that class a bit and add the logging when the mu plugin loads if sandboxed / proxied to get around it.

**Comment by joshbetz** [comment]
> which in our case happens at `init`

So we should be able to capture that by hooking on `set_current_user`, which happens before `init`.
