### ISSUE TITLE
2fa: Test and enable U2F

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#551]
https://github.com/georgestephanis/two-factor/pull/162

**Comment by sjinks** [comment]
U2F is no longer supported, WebAuthn is the replacement.

**Comment by joshbetz** [comment]
@sjinks it would still be nice to enable to U2F provider (or build a WebAuthn provider) https://github.com/WordPress/two-factor/blob/master/providers/class-two-factor-fido-u2f.php

**Comment by joshbetz** [comment]
Nevermind, this was fixed in https://github.com/Automattic/vip-go-mu-plugins/pull/1586 😄

**Comment by sjinks** [comment]
@joshbetz I actually wrote one: https://github.com/sjinks/wp-two-factor-provider-webauthn 😆
