### ISSUE TITLE
Jetpack Start: Improve information when Jetpack is found to be connected

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#552]
When I go to connect Jetpack with `wp jetpack-start connect` I sometimes find it's already connected. It would be good to get some extra information about that connection, so I can decide whether it needs reconnecting by VIP.

Of particular interest is which user is the master user.

**Comment by mjangda** [comment]
Maybe we can just output the result of the status command from #628
