### ISSUE TITLE
Jetpack Start CLI command: Improve hints when a user needs adding to the shadow site

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#554]
When connecting a site to Jetpack, the command can fail because the `wpcomvip` user is not added to the Jetpack shadow site… it would be useful to be more prescriptive about what the user should do in this situation.

**Comment by joshbetz** [comment]
Is there more context for this? Why does a user need to be added to a shadow site? What is "the command"?

**Comment by simonwheatley** [comment]
> Is there more context for this? Why does a user need to be added to a shadow site? What is "the command"?

Fair question. Added more context.
