### ISSUE TITLE
VaultPress shouldn't call its `do_pings` method on shutdown

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-go-mu-plugins#568]
Given VaultPress's support for cron-based triggering, and the platform's handling of cron, there's no need to also call VP's `do_pings()` method from the shutdown action. VP's requests can be long-running, so should be handled by cron to avoid any user-facing impact.

See https://github.com/Automattic/vip-go-mu-plugins/blob/5e7d0eb8bb14f563666111558e5466487ad779e3/vaultpress/vaultpress.php#L2470.

**Comment by ethitter** [comment]
This might be better as a flag in VP itself, but at least with it noted here, we won't lose track of the issue.

**Comment by rebeccahum** [comment]
Closing since VaultPress is being deprecated.
