### ISSUE TITLE
Jetpack Start: Adding user can fail if user exists with email

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#570]
If a user already exists with the machine user email, but not the new machine user login, the process will fail without printing an error message, when running `wp user create`.

https://github.com/Automattic/vip-go-mu-plugins/blob/b8d7c4c476d6cc9d61ab4352aced2f5d57d43b16/jetpack-start/wp-cli-api.php#L108

This can arise on older sites that have a machine user with a semi-random username.

We probably need to check for this user and delete it as part of the setup.

**Comment by mjangda** [comment]
Continued in #970
