### ISSUE TITLE
Upgrade CSSMin

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#574]
Upstream version of the YUI Minifier we're using has a bunch of updates including many bug fixes: https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/releases/tag/v3.1.1

**Comment by mjangda** [comment]
Upstream PR in concat plugin: https://github.com/Automattic/nginx-http-concat/pull/31

**Comment by ryanmarkel** [comment]
The upstream is now at 3.1.2. :)

**Comment by mjangda** [comment]
This was done.
