### ISSUE TITLE
WP User Activity?

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#593]
WP User Activity looks like a nice, easy way to add basic audit logging and seems easily extensible.

https://github.com/stuttter/wp-user-activity

**Comment by JJJ** [comment]
Hey, thanks! For highly active sites, it will need a clean-up routine to keep the number of logged items low. Once it gets into the hundreds of thousands, queries start to get pretty slow.

It wouldn't be very difficult to move this into a custom database table either. I have a base class for handling most of that stuff now, so let me know if that ever comes up as a need, and I can look into making a port that uses its own table instead.

**Comment by rebeccahum** [comment]
I'm not a fan of introducing another plugin maintained by a third-party and also, given ^ this has potential to bog things down. Closing.
