### ISSUE TITLE
Facing issue with jet pack in wp6.7 Mac os

### ISSUE THREAD

**Issue by naga909** [Automattic/vip-go-mu-plugins#6001]
The `/wp/wp-content/jetpack-waf` file cannot be managed by the `Automattic\VIP\Files\WP_Filesystem_VIP` class. Writes are only allowed for the `/tmp/` and `/wp/wp-content/uploads` directories and reads can be performed everywhere.

Os : Mac
Node : tried till 23 , 22, 18, 20.

Docker desktop: latest version 

Please find attached screenshot.![Image](https://github.com/user-attachments/assets/891a706a-2f5e-4ab1-a8c3-5f9be5e01c85)

**Comment by tallapallyn** [comment]
Hi Team , any update on above issue.
