### ISSUE TITLE
Set WP_CLI_PACKAGES_DIR

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#606]
By default wp-cli packages live in `getenv( 'HOME' ) . '/.wp-cli/packages/'`. This won't really work on VIP Go because for client sites that want to install packages, we'll have to run `wp package install` for each site and for each environment. On top of that, the home directory is thrown away each time you sandbox a site.

We should set the `WP_CLI_PACKAGES_DIR` to something inside the site repo. This way, packages can be submodules into the repo and magically work without `wp package install`. I'm thinking we'd either want to create a directory inside `plugins` or create a new directory specifically for wp-cli packages.

https://github.com/wp-cli/wp-cli/blob/d9d405a4ca01ba23e80277b8cb9000857e84e0cd/php/WP_CLI/Runner.php#L128

**Comment by rebeccahum** [comment]
`wp package *` is a disallowed command currently: https://docs.wpvip.com/technical-references/vip-cli/disallowed-commands/. Closing
