### ISSUE TITLE
wp search-replace, but for big sites

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#609]
`wp search-replace` breaks big sites. We probably shouldn't run it on live sites in general. In addition to the load, we need to be careful about direct DB queries that run for a long time before the cache is flushed.

**Comment by danielbachhuber** [comment]
Happy to discuss issues opened against https://github.com/wp-cli/search-replace-command/issues. I'd love to see `wp search-replace` improved for everyone.

**Comment by mjangda** [comment]
Yep, we'll upstream whatever we end up with.

**Comment by mjangda** [comment]
We're using https://github.com/Automattic/go-search-replace
