### ISSUE TITLE
Port WP.com's PHP Error Handler

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#636]
`wpcom_error_handler` and related code.

**Comment by ethitter** [comment]
On WP.com, these functions load just after `wp-config.php`, so I worry that `mu-plugins` won't be early enough. Even if we load this in `000-vip-init.php`, we'll miss anything that occurs while loading Core. Should we worry? Perhaps `vipd` should write the include into `wp-config.php`, while the functions themselves live in a subdirectory of mu-plugins?

**Comment by mjangda** [comment]
Good points and suggestion. We can put the code in `includes/lib` and require early from config via `vipd`.
