### ISSUE TITLE
Parse error: syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) 

### ISSUE THREAD

**Issue by emgk** [Automattic/vip-go-mu-plugins#641]
I am setting up the VIP environment using wamp server, I have cloned this repo using 
` git clone https://github.com/Automattic/vip-go-mu-plugins.git --recursive mu-plugins`  inside `wp-content` dir.

![screenshot-localhost-2017-07-04-12-10-17](https://cloud.githubusercontent.com/assets/14994452/26773228/fa48d7c0-49e7-11e7-819b-ace8dcb728cf.png)

Also, I have solved this error by commenting some codes, then when I visited the website, plugins are not activated yet. 

on the top of the website it's showing some paths like: 
`advanced-post-cache/advanced-post-cache.phpjetpack-start/jetpack-start.php./vip-cache-manager/vip-cache-manager.phpvip-dashboard/vip-dashboard.phpvip-support/vip-support.php`

**Comment by mjangda** [comment]
Looks like we need to drop the symbolic links so mu-plugins works on Windows.

Until then, I'd recommend using a Vagrant (or Docker) based dev environment like Chassis or VVV.

**Comment by emgk** [comment]
@mjangda By the symbolic link, you meant `advanced-post-cache/advanced-post-cache.phpjetpack-start/jetpack-start.php./vip-cache-manager/vip-cache-manager.phpvip-dashboard/vip-dashboard.phpvip-support/vip-support.php` ? if so, then I have tried to the same method in VVV dev environment in Windows but symbolic links but they don't seem to work there also.
