### ISSUE TITLE
Cache management for REST API requests

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#670]
As described in [our client documentation](https://vip.wordpress.com/documentation/vip-go/vip-go-and-the-wordpress-rest-api/#caching), we're going to start this off with a 1 minute TTL for all WordPress REST API requests.

**Comment by mjangda** [comment]
Super: #658

**Comment by mjangda** [comment]
FWIW, I have the code for this mostly done.
