### ISSUE TITLE
split-home-site-urls plugin should handle un-split domains

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-go-mu-plugins#674]
If `home` and `siteurl` are identical, the "split-home-site-urls" plugin creates a redirect loop. Though it clearly shouldn't be applied in this case, it also shouldn't break the site.

**Comment by Kluny** [comment]
Can I have some steps to reproduce? Is this something that would be possible to test on a local site? Is there any more to it than setting "WordPress Address (URL)" and "Site Address (URL)" to identical values in the general settings tab, then reloading the site ?

**Comment by ethitter** [comment]
To reproduce:
1. Set `home` and `siteurl` to identical values (including protocols)
2. Enable the _Support Split Home and Site Hosts_ plugin (part of `mu-plugins/shared-plugins`)
3. Try loading the homepage, and enjoy the redirect loop

Since none of the plugin's functionality is relevant if `home` and `siteurl` are identical, fixing this should be a matter of returning early in https://github.com/Automattic/vip-go-mu-plugins/blob/e1538838e873f82c0611386b61aabd138233a3f0/shared-plugins/split-home-site-urls/split-home-site-urls.php. Another option is to deactivate the plugin when identical values are detected.
