### ISSUE TITLE
Clearing transient `wpcom_media_months_array`

### ISSUE THREAD

**Issue by pkevan** [Automattic/vip-go-mu-plugins#717]
Currently the transient `wpcom_media_months_array` is never deleted because in the function `wpcom_vip_bust_media_months_cache` we are checking for a difference of time between the last attachment (https://github.com/Automattic/vip-go-mu-plugins/blob/master/performance/vip-tweaks.php#L45) and the attachment just uploaded, through the action `add_attachment`.

This means the transient is almost always never able to be removed.

We should check compare the dates stored in the transient against the new attachment id instead.

**Comment by rebeccahum** [comment]
Closing because already fixed by https://github.com/Automattic/vip-go-mu-plugins/pull/718.
