### ISSUE TITLE
Don't throw the error for certain CLI requests

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-go-mu-plugins#735]
For example, after using search-replace, one needs to flush the cache, which may not be possible due to the warning we throw.

https://github.com/Automattic/vip-go-mu-plugins/blob/92943b92f216cb8366be452eaf19fd777f50fb15/lib/sunrise/sunrise.php#L25

https://github.com/Automattic/vip-go-mu-plugins/blob/92943b92f216cb8366be452eaf19fd777f50fb15/lib/sunrise/sunrise.php#L44

**Comment by mjangda** [comment]
I think the error comes from wp-cli, not our code?

**Comment by ethitter** [comment]
I should've left more details. My recollection is that it was our message, but the strings are similar enough that I could've confused them. We can re-open if someone else encounters this.
