### ISSUE TITLE
Stop Woocommerce from trying to install files in read-only filesystem

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-go-mu-plugins#736]
Following https://github.com/woocommerce/woocommerce/pull/16601, we can use the `woocommerce_install_skip_create_files` filter to stop Woocommerce from trying to create files under a read-only filesystem.

**Comment by joshbetz** [comment]
Would it make sense for Woocommerce to check if the directory is writable instead of needing to add a filter?

**Comment by ethitter** [comment]
That was my original thought, but there are three or four files to check and/or create, in various directories. Also, these checks happen on `admin_init`, so I'm partial to bypassing them entirely.
