### ISSUE TITLE
Using https url for all submodules instead of ssh

### ISSUE THREAD

**Issue by PatelUtkarsh** [Automattic/vip-go-mu-plugins#750]
Pros: 
- Easy to clone for anyone even if their ssh public key is not added in GitHub.

Cons: 
- Any contributor who directly contributes using submodules need to add git remote using ssh.

**Comment by mjangda** [comment]
Thanks for the feedback @PatelUtkarsh!

We recommend using https://github.com/Automattic/vip-mu-plugins-public instead (especially if you're not an active developer for `vip-go-mu-plugins`). It's the "compiled" version of this repo, so you don't have to deal with submodules.
