### ISSUE TITLE
Add sslverify option to wpcom_vip_file_get_contents()

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/vip-go-mu-plugins#760]
Add an `sslverify` option to `wpcom_vip_file_get_contents()`, just as `wp_remote_get()` has.

**Comment by mjangda** [comment]
Why is that option needed?

**Comment by paulschreiber** [comment]
Local/development hosts often have self-signed certificates. Without this option, curl will fail to connect to them.

This has been in core since 2009:
https://core.trac.wordpress.org/ticket/8702

**Comment by rebeccahum** [comment]
Outdated, I think. This can be passed via `$extra_args` now: https://github.com/Automattic/vip-go-mu-plugins/blob/ba5fcff8bf5ca5b717675cf75fcb427aab77b5d4/vip-helpers/vip-utils.php#L540. Closing.
