### ISSUE TITLE
Filter jetpack into the active_plugins option

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#785]
Jetpack is always enabled...so if a client is using a local version of Jetpack from `plugins`, we need to filter it into the `active_plugins` option like we do for everything loaded via `wpcom_vip_load_plugin()`, otherwise JP looks inactive which could lead to people attempting to manually activate it via the UI.

Probably should filter it in there for 'normal' mu-plugin usages of JP too (no local version).

**Comment by simonwheatley** [comment]
Closing as wontfix in favour of https://github.com/Automattic/vip-go-mu-plugins/issues/797
