### ISSUE TITLE
Disable Jetpack Activation/Deactivation

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#788]
- [x] Suppress deactivation hooks
- [x] Suppress activation hooks
- [ ] Disable connecting from wp-admin (in favor of Jetpack Start)
- [ ] Disable activating via UI (in case of custom versions)?

**Comment by mjangda** [comment]
> Disable connecting from wp-admin (in favor of Jetpack Start)

This was implemented here: 

https://github.com/Automattic/vip-go-mu-plugins/pull/721

But is broken due to this Jetpack bug:

https://github.com/Automattic/jetpack/issues/8066
