### ISSUE TITLE
VIP Plugins: code active plugins get saved to database

### ISSUE THREAD

**Issue by david-binda** [Automattic/vip-go-mu-plugins#791]
There is a case in which plugins activated via `wpcom_vip_load_plugin` get saved in "active_plugins" to database. Which leads to a situation in which previously code activated plugin does not get deactivated when code is removed.

Test case:
1) One plugin active on the site via UI (has it's entry in database)
2) One plugin active via wpcom_vip_load_plugin
3) Visit wp-admin/plugins.php and activate some third plugin

Expected: only plugin mentioned in step 1 and 3 is in active_plugins option in database
Current: the plugin mentioned in step 2 is there as well
Symptom: get_option( 'active_plugins' ) contains a duplicate entry for plugin mentioned in step 2.

I'm not yet clear on why this happens :-/

**Comment by scottsweb** [comment]
Because `get_option` is filtered could it be simply that the data is filtered again as you retrieve it? Are you seeing the actual value in the DB table?

**Comment by david-binda** [comment]
Yep, I'm seeing the actual value in the DB.

wp-content/client-mu-plugins/plugin-loader.php :
```
wpcom_vip_load_plugin( 'test-plugin' );
```

Then I activated Hello Dolly. DB upon hello.php activation:
```
mysql> select * from wp_options where option_name = "active_plugins";
+-----------+----------------+----------------------------+----------+
| option_id | option_name    | option_value               | autoload |
+-----------+----------------+----------------------------+----------+
|        33 | active_plugins | a:1:{i:0;s:9:"hello.php";} | yes      |
+-----------+----------------+----------------------------+----------+
1 row in set (0.05 sec)
```

Then I activate test-plugin 2:

```
mysql> select * from wp_options where option_name = "active_plugins";
+-----------+----------------+-------------------------------------------------------------------------------------------------------+----------+
| option_id | option_name    | option_value                                                                                          | autoload |
+-----------+----------------+-------------------------------------------------------------------------------------------------------+----------+
|        33 | active_plugins | a:3:{i:0;s:9:"hello.php";i:1;s:24:"test-plugin-2/plugin.php";i:2;s:27:"test-plugin/test-plugin.php";} | yes      |
+-----------+----------------+-------------------------------------------------------------------------------------------------------+----------+
1 row in set (0.05 sec)
```

Removing the `wpcom_vip_load_plugin` code:

```
//wpcom_vip_load_plugin( 'test-plugin' );
```

Does not affect whether the plugin is or is not loaded. Just now, it is loaded via UI.

**Comment by dhanendrannewscorp** [comment]
@david-binda related issue https://github.com/Automattic/vip-go-mu-plugins/issues/785 and PR https://github.com/Automattic/vip-go-mu-plugins/pull/789
