### ISSUE TITLE
Photon working on go-vip.co domains only

### ISSUE THREAD

**Issue by david-binda** [Automattic/vip-go-mu-plugins#811]
The a8c-files mu-plugin automagically translates Photon URLs to VIP Go file service ones on sites running on go-vip.co domains. Which is usually the case on non-production environments and on production environments before the final URL is used.

Switching the URL to anything else than the default go-vip.co leads to breaking the behind the scenes rewrite and switches gears to real Photon URLs. Which, in turn, does not work until DNS are properly propagated.

We, imho, should either be rewriting all site's mapped domains in all environments, or disable the rewrite in non-production environments in order to make those more production like.

Related code: https://github.com/Automattic/vip-go-mu-plugins/blob/master/a8c-files.php#L748

**Comment by rebeccahum** [comment]
Outdated, I think.
