### ISSUE TITLE
Refactor build process to remove TravisCI dependency

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#822]
We should be able to run the build process (which pushes a 'compiled' version to Automattic/vip-go-mu-plugins-built) locally, independently of Travis, in case that service is down.

**Comment by rinatkhaziev** [comment]
This is handled by GHA now.
https://github.com/Automattic/vip-go-mu-plugins/blob/develop/.github/workflows/deploy.yml
