### ISSUE TITLE
[VIP Cache Manager] Escape percent signs in term URLs

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-go-mu-plugins#823]
In cases where the slug has percent signs, this causes a 'too few arguments warning' at https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-cache-manager/vip-cache-manager.php#L518 

For example, category name वर्ग has the slug %e0%a4%b5%e0%a4%b0%e0%a5%8d%e0%a4%97

Are there any downsides to a simple str_replace fix in the line above? e.g.
`str_replace( '%', '%%', $maybe_purge_url )`

**Comment by david-binda** [comment]
@trepmal how about not escaping the whole url, but only call `sprintf` with `$paging_endpoint` as a param? I have proposed the solution via #844
