### ISSUE TITLE
Always enable Debug Bar when sandboxed

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#831]
When VIP staff has a site sandboxed, they should be able to see the Debug Bar.

```
$enable = is_auttomattician() || WPCOM_SANDBOXED;
```

https://github.com/Automattic/vip-go-mu-plugins/blob/master/debug-bar.php#L12

**Comment by GaryJones** [comment]
Eventually closed via #1164.
