### ISSUE TITLE
Email wording to first user

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#84]
The email wording to the first user includes:

> Username: blahblahblah
> Password: The password you chose during the install.

We should change this to tell the user to use the forgotten password routine, or perhaps trigger a forgotten password email _instead_ of this email, so they can directly set their password.

**Comment by rinatkhaziev** [comment]
This is a core email so I'm not sure whether we should spend any time on this? @Automattic/vip-platform-cantina and @mjangda

**Comment by rebeccahum** [comment]
I don't think this is applicable anymore:

https://github.com/WordPress/WordPress/blob/82ee734e8bd72ba3dc85660aeadabe144ace3768/wp-includes/pluggable.php#L2194-L2197

When you create a user, you get:

```
Username: TestUser

To set your password, visit the following address:
```

Closing.
