### ISSUE TITLE
Add a LIMIT / loop to transient deletion in migration cleanup

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#842]
`Automattic\VIP\Migration\delete_db_transients()` should have a reasonable LIMIT, and do any additional deletions in a loop (with a delay), to go easy on db servers / replication when there are many transients.

**Comment by mjangda** [comment]
@joshbetz is right; this is adding unnecessary complexity and we can leave as-is.
