### ISSUE TITLE
Surface login / 2fa restrictions for wpcomvip account

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#863]
In #518 we blocked logins for the `wpcomvip` account. However, when viewed in the users list, it just looks like any other user and shows 2fa is inactive, which is not great.

It would be nice to do a couple of things:

- Surface the fact that this is a machine user and its purpose.
- Surface the fact that logins are blocked or that this account has extra protections.
- Bonus: block editing / deletion of the account.

h/t @mdrovdahl

**Comment by rebeccahum** [comment]
Looks like these protections have been added in place: https://github.com/Automattic/vip-go-mu-plugins/blob/fdd99cf535e55eeda46d7a11a4cbb1603d8bc666/security/machine-user.php. In [our docs](https://docs.wpvip.com/technical-references/wordpress-on-vip/), we have:

> Jetpack, Akismet, and VaultPress are registered with the VIP machine user wpcomvip. This machine user is required for managing Jetpack connections and should not be removed. Logins for the wpcomvip user are restricted.

Closing. Feel free to re-open if you think this still needs work.
