### ISSUE TITLE
Vaultpress - Deprecated function - PHP 7.2

### ISSUE THREAD

**Issue by rodruiz** [Automattic/vip-go-mu-plugins#867]
Hi,
PHP 7.2 was [Deployed on VIP Go](https://lobby.vip.wordpress.com/2018/04/06/php-7-2-deployed-on-vip-go/). I'm using VVV for local development and updated the local environment to 7.2 as well.
```error
PHP Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /srv/www/wordpress-default/public_html/wp-content/mu-plugins/vaultpress/cron-tasks.php on line 111
```
See: [Line 111](https://github.com/Automattic/vip-go-mu-plugins/blob/master/vaultpress/cron-tasks.php#L111)

See [PHP documentation](http://php.net/manual/en/function.each.php) and [deprecations_php_7_2#each](https://wiki.php.net/rfc/deprecations_php_7_2#each)

Thank you.

**Comment by GaryJones** [comment]
This appears to now be fixed.
