### ISSUE TITLE
WP_Filesystem_VIP: Add caching to read methods

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#878]
We should look into adding caching to read methods in `WP_FIlesystem_VIP_Uploads` where appropriate and invalidation for the write methods.

**Comment by rebeccahum** [comment]
Looks like this has been implemented already by https://github.com/Automattic/vip-go-mu-plugins/blob/develop/files/class-api-cache.php. Closing, feel free to re-open if I misunderstood the assignment.
