### ISSUE TITLE
Don't silently handle missing plugins on VIP environments

### ISSUE THREAD

**Issue by johnbillion** [Automattic/vip-go-mu-plugins#883]
If `wpcom_vip_load_plugin()` is called with a file name that doesn't exist, it exits with an error message, but only on non-VIP environments. Ref: https://github.com/Automattic/vip-go-mu-plugins/blob/95a3597ecc988e846f9dcaf4c8d8ed693c79098e/vip-helpers/vip-utils.php#L1061-L1063

If the same situation is encountered on a VIP environment then the problem is silently discarded. If, for example, the theme on the site directly calls functions from the missing plugin then it'll raise a fatal error, but if it has guard conditions in place then everything will fail silently.

As a safeguard, I would like this condition to raise a PHP warning on VIP environments. Thoughts?

**Comment by chrean** [comment]
@mjangda and @johnbillion just for confirmation, do we want this to behave on VIP like it does on WPCOM i.e. dying on missing plugins, or do we want it to do something different?

**Comment by johnbillion** [comment]
Personally I think it should raise a PHP warning on VIP environments.

**Comment by johnbillion** [comment]
Although those warnings would need to be exposed to the client too. Maybe hook it up to the New Relic alerting with `newrelic_notice_error()`.
