### ISSUE TITLE
Rename 000-debug/logger.php Timer (e) Function

### ISSUE THREAD

**Issue by hughdevore** [Automattic/vip-go-mu-plugins#887]
I'm currently trying to add codeception via [wp-browser](https://github.com/lucatume/wp-browser) however I get an error:

```
Fatal error: Cannot redeclare e() (previously declared in /Users/hughie/Code/wp-content/client-mu-plugins/vendor/illuminate/support/helpers.php:574) in /Users/hughie/Code/wp-content/mu-plugins/000-debug/logger.php on line 196
```

The function here conflicts with a dependency in wp-browser:
https://github.com/Automattic/vip-go-mu-plugins/blob/master/000-debug/logger.php#L187

and is only used here: 
https://github.com/Automattic/vip-go-mu-plugins/blob/master/000-debug/logger.php#L208

Is there anyway we could change this to something like `timer()` so that this conflict no longer happens? If not, is there another way I could get around this? I have tested the function name change locally and it works as expected.

**Comment by oppodeldoc** [comment]
I second this request. The newest version of the Sage theme (which we'd like to use on VIP) leverages Laravel's support library which tries to use `e()` as an escape shortcut everywhere and this breaks it. Their code gracefully declines to override the function in this debug plugin:
https://github.com/illuminate/support/blob/master/helpers.php#L550

This is going to make it tough for us to use our desired workflow here. Possible to escalate this?

**Comment by mjangda** [comment]
Thanks @oppodeldoc (and sorry for not getting to this sooner @hughdevore). We've renamed the functions so hopefully fewer headaches for y'all.

**Comment by oppodeldoc** [comment]
@mjangda Many thanks!
