### ISSUE TITLE
The "Learn More" link leads to a 404 for most shared plugins

### ISSUE THREAD

**Issue by johnbillion** [Automattic/vip-go-mu-plugins#902]
On the Plugins screen at `wp-admin/plugins.php`, the table that lists plugins in the `mu-plugins/shared-plugins` directory right at the bottom of the screen (below the regular plugins table) displays a "Learn More" link next to each plugin.

For most of the plugins in this list, this link leads to a 404. For example, https://vip.wordpress.com/plugins/two-factor/.

**Comment by scottsweb** [comment]
Hi John, where abouts are you seeing this? I am fairly certain this could be due to an old `vip-dashboard` sub-module as I think we stripped out the custom tables and the majority of the shared plugins now.

**Comment by johnbillion** [comment]
Ah yes you're right, this is an out of date local submodule. The site on VIP no longer shows this table.
