### ISSUE TITLE
wp migration dbdelta command doesn't return results

### ISSUE THREAD

**Issue by emrikol** [Automattic/vip-go-mu-plugins#903]
It looks like something is off at the end of the dbdelta command.  After runnning it I get this as a result:

```
$ wp vip migration dbdelta
Changed type of wp_options.option_name from varchar(64) to varchar(191)
Added index wp_postmeta KEY `vip_meta_key_value` (`meta_key`(191),`meta_value`(100))
Changed type of wp_posts.post_password from varchar(20) to varchar(255)
Success: %s changes
```

The problem line is probably here: https://github.com/Automattic/vip-go-mu-plugins/blob/8cc468734612419c95a5cafae6670aaf71036da9/wp-cli/vip-migrations.php#L161

I don't have time to look into it this second, so I'm opening this for posterity so we don't forget.

**Comment by mjangda** [comment]
We're missing a sprintf.
