### ISSUE TITLE
No index non production sites with a custom domain

### ISSUE THREAD

**Issue by scottsweb** [Automattic/vip-go-mu-plugins#904]
By default all *.go-vip.co domains have a no-index HTTP header automagically added. If the non-production environment uses a different domain this does not happen and protection needs to be added explicitly.

Possible fix:

```
<?php 
 
if ( 'production' !== VIP_GO_ENV ) {
    header( 'X-Robots-Tag: noindex, nofollow', true );
}
```

**Comment by chrean** [comment]
Adding refs for tracking purposes:

- https://veetoop2.wordpress.com/2018/05/24/id-like-to-remove-the/
- https://veetoop2.wordpress.com/2018/05/24/smart-defaults-after-data-sync/

**Comment by simonwheatley** [comment]
> No index non production sites with a custom domain

I think we could try doing this for all domains, not just custom domains.

**Comment by chrean** [comment]
Merged https://github.com/Automattic/vip-go-mu-plugins/pull/911

**Comment by chrean** [comment]
r112439-deploy
