### ISSUE TITLE
PURGE varnish when home_url changes

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#91]

**Comment by nickdaugherty** [comment]
If the domain is changing, then presumably requests will be going to that new url, which in itself will cause cache invalidations. Purging the old domain wouldn't have a large effect, right?

**Comment by nickdaugherty** [comment]
Actually this is the same as #528. Since that one has more details (the issue is potential redirect loops), let's close this in favor of that one.
