### ISSUE TITLE
[NewRelic] Wrap logging into a separate library/function?

### ISSUE THREAD

**Issue by chrean** [Automattic/vip-go-mu-plugins#913]
As we have just added logging for missing plugins on VIP envos (see https://github.com/Automattic/vip-go-mu-plugins/issues/883 ), @mjangda suggested it might be worth looking into wrapping error message generation in a separate library/function.

Code involved:

https://github.com/Automattic/vip-go-mu-plugins/blob/50a172022c97e2bcbe7218756692227cb0abecda/vip-helpers/vip-utils.php#L1056-L1072

So basically we'd create a function/library which will both:

a) print out a warning
b) create an alert on New Relic if the extension is present

**Comment by mjangda** [comment]
The WooCommerce.com team has a nice simple PSR-style logger that would be interesting to make available to all clients.

**Comment by rinatkhaziev** [comment]
Customers have means to access logs these days, closing.
