### ISSUE TITLE
Intermittent "Trying to get property 'id' of non-object" error

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/vip-go-mu-plugins#916]
On /wp-admin/, we occasionally see:
    Trying to get property 'id' of non-object

from wp-content/mu-plugins/vip-plugins/vip-plugins.php:152

```php
function wpcom_vip_plugin_action_links( $actions, $plugin_file, $plugin_data, $context ) {
	$screen = get_current_screen();
	if ( in_array( $plugin_file, wpcom_vip_get_filtered_loaded_plugins(), true ) ) {
		if ( array_key_exists( 'activate', $actions ) ) {
			unset( $actions['activate'] );
		}
		if ( array_key_exists( 'deactivate', $actions ) ) {
			unset( $actions['deactivate'] );
		}
		$actions['vip-code-activated-plugin'] = __( 'Enabled via code', 'vip-plugins-dashboard' );
		if ( 'plugins' === $screen->id ) {
			unset( $actions['network_active'] );
		}
	}
	return $actions;
}
```

If `$screen` isn't an object, don't call `$screen->id`.

**Comment by mjangda** [comment]
Do you have an example path where this is occurring? `/wp-admin/`? Or is it a specific admin page?

**Comment by paulschreiber** [comment]
I only noticed it on /wp-admin/. It went away after a reload.

**Comment by rinatkhaziev** [comment]
This was fixed: https://github.com/Automattic/vip-go-mu-plugins/blob/develop/vip-plugins/vip-plugins.php#L155
