### ISSUE TITLE
Don't check for restricted usernames in non-VIP environments

### ISSUE THREAD

**Issue by chrisscott** [Automattic/vip-go-mu-plugins#921]
On local environments it is likely that `admin` is used as a login, however, `security.php` prevents this from being used for authentication. This can prevent logins when content is imported locally with that username or a user is created on a fresh install before these plugins are added. This could also happen if a content import or user chose the machine name of `vip`.

**Comment by rebeccahum** [comment]
Closing this based on https://github.com/Automattic/vip-go-mu-plugins/pull/915#issuecomment-459213558.
