### ISSUE TITLE
Potential PHP Notice in VaultPress - undefined var `$function`

### ISSUE THREAD

**Issue by jakewrfoster** [Automattic/vip-go-mu-plugins#922]
It appears as though [this line in VaultPress](https://github.com/Automattic/vip-go-mu-plugins/blob/7c6e0198e8f98b1e81bdbeacbeed4ad22afab8da/vaultpress/vaultpress.php#L1548) would potentially throw a PHP Notice due to `$function` not being defined before it is self-assigned.

**Comment by simonwheatley** [comment]
I've passed this on to our VaultPress colleagues in Automattic, thank you @jakewrfoster!

**Comment by jakewrfoster** [comment]
np! thanks!

**Comment by GaryJones** [comment]
@jeherve Seems like this self-assignment still exists [upstream](https://github.com/Automattic/vaultpress/blob/2bcf646f4e898af0a1f9a8a2fa5ad16ff2efceed/vaultpress.php#L2039). Can't see an issue open for it, but something tells me this line is somewhat redundant anyway?

**Comment by jeherve** [comment]
cc @briancolinger who should be more familiar with this than I am.

**Comment by rebeccahum** [comment]
Closing since VaultPress is being deprecated.
