### ISSUE TITLE
Update A8C Files to use Api_Client 

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#933]
The API interactions in [`a8c-files.php`](https://github.com/Automattic/vip-go-mu-plugins/blob/master/a8c-files.php) should be updated to use our [Api_Client class](https://github.com/Automattic/vip-go-mu-plugins/blob/master/files/class-api-client.php) (i.e. instead of the direct `curl` calls).

- [x] `A8c_Files::_check_uniqueness_with_backend()`
- [x] `A8c_Files::attachment_file_exists()`
- [x] `A8c_Files::upload_file()`
- [x] `A8c_Files::delete_file()`

Would also be great to add some test coverage for these methods as well.

**Comment by dchymko** [comment]
The last three methods exist in `Api_Client` but I'll have to add  an implementation of `_check_uniqueness_with_backend()` to it.

**Comment by dchymko** [comment]
See #941

**Comment by mjangda** [comment]
Closing; most of a8c-files will be going away with the Stream Wrapper implementation.
