### ISSUE TITLE
Go sites can't delete and replace media files with identical filenames

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/vip-go-mu-plugins#934]
This has been tested both on a Go installation and in a non-Go core context, and the behavior is different.

## Use Case

I have a PDF that I know has been externally linked or that I have used a shortlinking service to point to. One of my staff has noticed a rather egregious error in the document, and now I need to replace the PDF with a new copy that has the same exact filename.

## Core Behavior

1. I delete the original file.
2. I upload the replacement file.
3. I check the new file; it has exactly the same filename and the swap is successful.

## Go Behavior

1. I delete the original file from the Media Library.
2. I upload the replacement file.
3. I check the new file; it does not have the same filename. A number has been appended to the filename itself. (e.g. myawesomepdf2.pdf)

**Comment by ryanmarkel** [comment]
Whatever is done for this would also need to instruct the platform to purge edges, or the replacement will not appear to work.

**Comment by rebeccahum** [comment]
https://github.com/Automattic/vip-go-mu-plugins/blob/3ee0c9f6d23ccd8e795be7b36e78af06a77d2fa3/a8c-files.php#L325

This would require some logic to bypass `wp_unique_filename()`.

**Comment by rebeccahum** [comment]
Tested and seems to be no longer applicable.
