### ISSUE TITLE
Display mu-bundled plugins on Plugins page

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#936]
We bundle quite a few plugins as part of `mu-plugins` (Debug Bar, Query Monitor, Rewrite Rules Inspector, Jetpack, etc.).

We should make sure that these plugins are included on the Plugins page to make it clear that they are already available for use. The activate/deactivate links should be removed/deactivated since the plugins are auto-loaded.

**Comment by TheCrowned** [comment]
Leaving a note just to say I am looking into this :)

**Comment by joshbetz** [comment]
They show up on the 'Must Use' plugins page (/wp-admin/plugins.php?plugin_status=mustuse). Is it worth changing the core UI here?

**Comment by rebeccahum** [comment]
I think them showing up on the "Must Use" plugins page is enough. Ideally, if a user attempts to add another version onto their plugins folder, the plugin itself should be self-aware to not attempt to load it again.
