### ISSUE TITLE
Update or remove the overridden Query Monitor DB collector

### ISSUE THREAD

**Issue by johnbillion** [Automattic/vip-go-mu-plugins#937]
On VIP Go, the DB collector for Query Monitor is overridden. Refs:

* https://github.com/Automattic/vip-go-mu-plugins/blob/2907a25efa717178392b3f0daa71ae271b41dc77/query-monitor.php#L116-L122
* https://github.com/Automattic/vip-go-mu-plugins/blob/2907a25efa717178392b3f0daa71ae271b41dc77/vip-helpers/vip-query-monitor.php

This collector is somewhat behind Query Monitor's own `QM_Collector_DB_Queries` and is causing undefined index PHP notices. Ref: https://github.com/johnbillion/query-monitor/issues/333

This class either needs to be updated to the latest code from QM, or removed, but I'm not sure of the reason for its existence, so I guess it's needed.

**Comment by justnorris** [comment]
:wave: Hey @johnbillion - I forgot to add a reference to #930 in https://github.com/johnbillion/query-monitor/issues/333 - I tracked the issue down and ported your changes over to the VIP Query Monitor.
