### ISSUE TITLE
JS concatenation breaks Gutenberg views

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/vip-go-mu-plugins#938]
## Summary

When attempting to use Gutenberg as a primary editor, attempts to load the post edit panel will fail with a blank edit space. This appears to be the result of a loading error caused by VIP Go's JavaScript concatenation methods.

![screen shot 2018-07-17 at 9 05 48 am](https://user-images.githubusercontent.com/4636317/42822413-9d6002d2-89a0-11e8-9f28-f740a2ac589d.png)

## Reproduction/Testing Steps

1. Load Gutenberg and ensure it's being loaded by setting config for Gutenberg Ramp.
2. Attempt to create a new post by going to Posts > New Post.
3. The screen will be largely blank, as seen in the previous screen capture.
4. Change the URL of the page by adding the query string `concat_js=no`.
5. Gutenberg loads successfully.

**Comment by mjangda** [comment]
Closing this for now as we've implemented other workarounds (initially disabling script concat for gutenberg, now skipping concat only for scripts with inline data.
