### ISSUE TITLE
VIP Support: Show notice when not proxied

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#951]
If a request is not proxied, the VIP Support role doesn't work as expected. If a user with a VIP Support role visits a site without the proxy, we should show an error or notice of some kind to make that clear.

Can probably use a similar badge as the `sandboxed` one.

**Comment by shantanu2704** [comment]
Hi @mjangda! 
I was thinking of using the `[is_proxied_automattician()](https://github.com/Automattic/vip-go-mu-plugins/blob/f6dee92dc75006b95a4f7a0c90d1bbe93ca3bfaa/vip-helpers/vip-utils.php#L1263)` function to check if the visitor is using the a8c proxy. Is that what you had in mind?

**Comment by rebeccahum** [comment]
Looks like this has been added: https://github.com/Automattic/vip-go-mu-plugins/blob/fdd99cf535e55eeda46d7a11a4cbb1603d8bc666/000-debug/not-proxied-flag.php

Closing.
