### ISSUE TITLE
Add an 'A11n Only' note to the Purge Cache button

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#961]
The button lives in WP Admin dashboard but is only accessible to Automatticians, so it should be labeled as such to make it clear to ourselves that end-clients don't have access to the button.

https://github.com/Automattic/vip-go-mu-plugins/blob/da7fcd24b773e1957687c6eb56f0b56ddd402d9e/vip-cache-manager/vip-cache-manager.php#L57-L70

**Comment by WPprodigy** [comment]
Located here (TIL): 
![dashboard](https://user-images.githubusercontent.com/8536129/44708094-d9607500-aa6b-11e8-8351-891785a2f3cc.png)
