### ISSUE TITLE
Priority too low for forcing HTTPS in REST API

### ISSUE THREAD

**Issue by pyronaur** [Automattic/vip-go-mu-plugins#969]
VIP Go requires SSL for the REST API and is automagically returning `https://` version of the rest API.

https://github.com/Automattic/vip-go-mu-plugins/blob/da7fcd24b773e1957687c6eb56f0b56ddd402d9e/misc.php#L85-L96

However, because this is a `mu-plugin` it's likely going to run this filter before anyone else on priority 10, which means that it's easy to accidentally override the VIP Go `https://` link version with a `http://` by doing this (in theme functions.php for example):

```php
add_filter('rest_url', function() { return 'http://site.com'; } );
```

To fix this, clients need to either do this:

```php
add_filter('rest_url', function() { return 'http://site.com'; }, 8 );
```

Or, what I think would be a better solution - we could make the filter run later:

```php
/**
 * On Go, all API usage must be over HTTPS for security
 *
 * Filter `rest_url` to always return the https:// version
 *
 * This is disabled for local development, but be aware
 * that HTTPS is enforced at the web server level in production,
 * meaning non-HTTPS API calls will result in a 406 error.
 * 
 * Priority 100 to force HTTPS when rest_url is modified
 * from outside mu-plugins (for example from theme functions.php)
 */
if ( defined( 'WPCOM_IS_VIP_ENV' ) && true === WPCOM_IS_VIP_ENV ) {
	add_filter( 'rest_url', '_vip_filter_rest_url_for_ssl', 100 );
}
```

Would/could this change break something for existing sites?

**Comment by mjangda** [comment]
I'm curious why sites are returning an `http` URL for their overrides? That seems like the key issue here.

In any case, it wouldn't hurt to bump the priority. However, we should probably move the `WPCOM_IS_VIP_ENV` check inside `_vip_filter_rest_url_for_ssl` instead. That way, the callback is visible and fires in local environments and would simplify debugging.

**Comment by justnorris** [comment]
> I'm curious why sites are returning an http URL for their overrides? That seems like the key issue here.

I discovered this because a site was using http://*.com in their settings and it dawned on me that it's a possibility for things to break this way.

I agree that nobody should be using `http://` anywhere, but then we wouldn't need this filter :) ?

> However, we should probably move the WPCOM_IS_VIP_ENV check inside _vip_filter_rest_url_for_ssl instead. That way, the callback is visible and fires in local environments and would simplify debugging.

Sounds like a good idea.
