### ISSUE TITLE
Jetpack start - creating new user can silently fail

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-go-mu-plugins#970]
https://github.com/Automattic/vip-go-mu-plugins/blob/8381c4300f1d774515213fafd2e215f06461e038/jetpack-start/wp-cli-api.php#L210

If `WP_CLI::runcommand()` fails, the script exits and no message is reported to the user.

## Scenario

Site uses `limited_email_domains` to restrict user registration.
```
$ wp site option get limited_email_domains
array (
  0 => 'example.com',
)
```

Internally, the `wp user create` command fails

```
$ wp user create --role='administrator' --display_name='Frank' --porcelain 'frank' 'frank@local.wordpress.test'
Error: Sorry, that email address is not allowed!
```

# Possible solution

Change the options in `runcommand()` so it 1) doesn't exit and 2) returns the error message

```
$user_id = WP_CLI::runcommand( $cmd, [
	'return' => 'all',
	'exit_error' => false,
] );
```

`$user_id` will then be an object returning both stdout and stderr:

```
$user = get_userdata( $user_id->stdout );

if ( ! $user ) {
	return new WP_Error( 'maybe_create_user-failed', $user_id->stderr ?: 'Failed to create new user.' );
```

# Second solution

For this exact scenario, perhaps we should whitelist ourselves:

```
add_filter( 'site_option_limited_email_domains', function( $value ) {
	$value = (array) $value;
	$value[] = 'example.com';
	return $value;
});
```

**Comment by uxcitizen** [comment]
cc @mdbitz

**Comment by mjangda** [comment]
"Second Solution" seems reasonable. Can you put together a PR @trepmal?

**Comment by mjangda** [comment]
Actually, I guess, probably worth doing both in case the user creation fails for some other reason.

**Comment by joshbetz** [comment]
I'm running into this in https://github.com/Automattic/vip-go-mu-plugins/pull/988 as well.

`\WP_CLI::runcommand( sprintf( 'jetpack-start connect --url=%s', home_url() )` exits silently on my sandbox without even logging an error.

We may want to adopt something like solution 1 anywhere we're using `runcommand` to force errors to be logged.

**Comment by rebeccahum** [comment]
Logic has changed where [this is no longer applicable](https://github.com/Automattic/vip-go-mu-plugins/blob/fdd99cf535e55eeda46d7a11a4cbb1603d8bc666/vip-jetpack/connection-pilot/class-jetpack-connection-cli.php#L32-L35), closing.
