### ISSUE TITLE
Jetpack Start: Switch to new bin scripts

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-mu-plugins#973]
We're currently using older, copied versions of the bin scripts. 

We should upgrade to the newer ones as they rely on newer versions of the API which has seen several improvements. Will need to see if we can use the scripts as-is or they need modifications to work with our flow.

https://github.com/Automattic/jetpack/tree/master/bin

**Comment by WPprodigy** [comment]
Closing per #2634.
