### ISSUE TITLE
"Undefined index" warning in vip-caching.php

### ISSUE THREAD

**Issue by gmazzap** [Automattic/vip-go-mu-plugins#976]
The function `wpcom_vip_maybe_skip_old_slug_redirect` (https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-helpers/vip-caching.php#L712-L720) in our local environment produces a warning: `Undefined index: DOCUMENT_URI`.

In our systems, the server variable `DOCUMENT_URI` is not defined, we have the same value in `REQUEST_URI`, instead.

This might not be an issue on VIP servers, but should be took into account for local environements. This is filling our local logs as it happens at every frontend request.

Considering that min PHP version is now 7.2, I would suggest something like this:

```php
$uri = $_SERVER['DOCUMENT_URI'] ?? $_SERVER['REQUEST_URI'] ?? null;

// We look to see if a malformed url (represented by 'http:' ) is right after the starting / in DOCUMENT_URI hence position 1
if ( is_404() && ( 1 === strpos( $uri, 'http:' ) || 1 === strpos( $uri, 'https:' ) ) ) {
```

which is both readable and fix the issue.

An alternative could be using `add_query_arg()` function so avoid direct access to `$_SERVER` values at all.

It worth nothing that `add_query_arg()` uses `REQUEST_URI` not `DOCUMENT_URI`.

**Comment by GaryJones** [comment]
@gmazzap Thanks for your patience!
