### ISSUE TITLE
php warning - hash_equals() expects strings

### ISSUE THREAD

**Issue by davidsword** [Automattic/vip-go-mu-plugins#977]
I came across

```
Warning: hash_equals(): Expected user_string to be a string, integer given 
in lib/proxy/ip-forward.php on line 175
```

https://github.com/Automattic/vip-go-mu-plugins/blob/master/lib/proxy/ip-forward.php#L175

The integer looks like it can come from `get_proxy_verification_key()` which returns `rand()` if `WPCOM_VIP_PROXY_VERIFICATION` is undefined.

https://github.com/Automattic/vip-go-mu-plugins/blob/master/lib/proxy/ip-forward.php#L157

I am wondering if there was a deliberate reason for returning an integer, or if `rand()` should be casted as a string.

**Comment by mjangda** [comment]
> I am wondering if there was a deliberate reason for returning an integer, or if rand() should be casted as a string.

Not intentional; casting as a string seems reasonable.

**Comment by mjangda** [comment]
This was fixed.
