### ISSUE TITLE
Can you install VIP Go MU Plugins in self-hosted Wordpress.org instance?

### ISSUE THREAD

**Issue by LevanArabuli** [Automattic/vip-go-mu-plugins#979]
I want to install self-hosted Wordpress.org plus VIP Go MU Plugins to make it similar to hosted VIP Go.
For various reasons I can't use Vagrant and VVV, instead I want to add these plugins to fresh Wordpress.org self-hosted instance. Is there a guide on how to do it? 

I tried # 3 step from [VIP Go local development guide](https://vip.wordpress.com/documentation/vip-go/local-vip-go-development-environment) but it didn't work.

**Comment by mjangda** [comment]
Yes, you should be able to use this repo outside of VVV.

> I tried # 3 step from VIP Go local development guide but it didn't work.

What specifically didn't work?
